import React, { useState } from "react";
import Grid from "@mui/material/Grid";
import MDBox from "components/MDBox";
import { useParams } from "react-router-dom";
import DashboardLayout from "examples/LayoutContainers/DashboardLayout";
import DashboardNavbar from "examples/Navbars/DashboardNavbar";
import Footer from "examples/Footer";
import Formulario from "components/Formulario";

function AltaInspeccion() {
  const { id } = useParams();
  const steps = [
    {
      label: "Info General",
      fields: [
        { type: "date", label: "Fecha de inspección", name: "fecha", required: true },
        { type: "number", label: "Expediente", name: "expediente" },
        { type: "text", label: "Inspector", name: "inspector" },
        { type: "text", label: "Departamento", name: "departamento" },
        { type: "text", label: "Empresa", name: "empresa" },
        {
          type: "select",
          label: "Dirección",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "balizaFlash/GetAll",
          valueField: "balizaFlash",
          optionField: "balizaFlash",
        },
        {
          type: "select",
          label: "Representante tecnico",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "antena.balizaFlash/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        { type: "text", label: "Nombre del sitio", name: "nombre del sitio", required: true },
        { type: "number", label: "Código del sitio", name: "codigo del sitio " },
        { type: "tetx", label: "Dirección", name: "direccion" },
        { type: "text", label: "Localidad", name: "localidad" },
        { type: "text", label: "Partido", name: "partido" },
        { type: "text", label: "Provincia", name: "provincia" },
        { type: "text", label: "Emplazamiento", name: "emplazamiento" },
        { type: "text", label: "A nivel", name: "nivel" },
        { type: "text", label: "En edificio", name: "edificio" },
        {
          type: "select",
          label: "Tipo estructura",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        { type: "text", label: "Altura soporte", name: "altura soporte", required: true },
        { type: "number", label: "Altura total", name: "altura total " },
        { type: "tetx", label: "Tipo de sala de equipo", name: "tipo de sala de equipo" },
        { type: "text", label: "Localidad", name: "localidad" },
        {
          type: "select",
          label: "Tipo de mimetizado",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        { type: "text-area", label: "observacion", name: "observacion" },
        { type: "checkbox", label: "Habilitado", name: "habilitado" },
      ],
    },
    /*-----------------------------------------------------------------------------*/
    {
      label: "Inspección visual",
      fields: [
        {
          type: "select",
          label: "Porton de acceso a la estación, estado de cerradura",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Alambrado perimetral y cocertina de seguridad",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Desmalezado, dranajes y limpieza del área de ocupación de la estación",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Cámaras de pase. (puesta tierra, fo, energia)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Obstrucciones en caños soterrados (puesta a tierra, fo, energia)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        { type: "checkbox", label: "Habilitado", name: "habilitado" },
        {
          type: "select",
          label: "Escalera de ascenso con guarda hombre",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Plataforms de inspección de antenas",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Salva caídas (Cable de vida)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Soportes y fijaciones de bandejas guias de onda desde quípos a antenas",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Soporte y fijaciones de cañerias desde equipos a antenas",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Pilar de medición de energia o gabinete de medición en edifició",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Tablero principal (estanqueidad, sombolo de siesgo eléctrico)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Canalización entre pilar de medición en edificio",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Dispositivo de protección termomagnético principal",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Cámara de inspección y jabalina en pilar de energía (de corresponder)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Verticalidad y torsión ( aplica a todos los tipos de estructuras)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Bulones, tuercas y arandelas",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Estructura de transición o apoyo en Azotea",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Soportes y fijaciones de celdas, RRU y filtros sobre estructura",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Uniones entre tramos (bridas en el caso de monopolos)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Objetos extraños (presencia de nidos de aves)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Estado general (corrosión, pintura, etc.)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
      ],
    },
    /*---------------------------------------------------------------------------------------------*/
    {
      label: "Banquina de equipos",
      fields: [
        {
          type: "select",
          label: "Base de concreto principal (para torre auto soportada a nivel 0)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Base de comcreto ( para banquinas de equipos a nivel 0)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Pernos de fijación entre base de concreto y pedestrales o tirantes",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Pernos de fijación entre bases de concreto y estructura de monopolio",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Pernos de fijación entre viga de acero y sala de equipos",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Pedestal de concreto para anclajes de riendas (mástil)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Pernos de fijación entre pedestal de concreto y perfil de acero",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Grietas y/o fisuras en pedestales de concreto",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Desplazamientos o fisuras en el suelo o loza azotea",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Rotura entorno pedestales de concreto de anclajes",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Puntos de acumulación de humedad",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Erosión del terreno entorno a la base de concreto (torres a nivel 0)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Luces para balizamiento nocturno",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Cables de alimentación balizas",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Estanqueidad de cañerias, cajas de pase y conectores",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Soporte para balizas",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Tablero  de balizamiento",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Estado de fotocélula",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Pintura para balizamiento diurno sobre estructura (Naranja / Blanco)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Visibilidad a los 100 mts",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Baliza Flash ( si corresponde)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "UCLA (Unidad de control de lámpara apagada)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
      ],
    },
    /*---------------------------------------------------------------------------------*/
    {
      label: "Equipos Shelter",
      fields: [
        {
          type: "select",
          label: "Tablero general de corriente alterna",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Tablero de emergencia para grupo electrógeno",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Pernos de fijación entre gabinetes y viga de aceri de apoyo shelter",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Viga de apoyo para sala de equipos. (estado general)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Símbolo de riesgo eléctrico en gabinetes de equipos energizados",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Puerta de acceso y cerramiento de sector banquina de equipos",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Iluminación sector banquinas de equipos",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Pintura sector banquina de equipos",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Cámara de inspección y jabalinas (Limpieza, rótulo de puesta a tierra)",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Conexión entre barra de conexión de tierra y anillo de puesta a tierra",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Conexión a tierra entre anillo de puesta a tierra y gabinetes",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Barra de conexión de puesta a tierra montada e estructura",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Barra de conexión de puesta a tierra equipos y guias de onda",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Grasa antioxidante en terminales de conexion a tierra",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Anillo o alo de puesta a tierra en banquina de equipos",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Conexión a tierra de puerta y chasis gabinetes equipos exteriores",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Conexión de tierra entre barra de tierra estructura y anillo P.A.T.",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Punta captora",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Mástil",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Cable de descarga a tierra pararrayos",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
        {
          type: "select",
          label: "Cámara de inspección puesta a tierra pararrayos",
          name: "idCalle",
          apiUrl: process.env.REACT_APP_API_URL + "calle/GetAll",
          valueField: "idCalle",
          optionField: "nombre",
        },
      ],
    },
  ];

  const apiUrl = process.env.REACT_APP_API_URL + `ANT_Inspecciones`;

  return (
    <DashboardLayout>
      <DashboardNavbar />
      <MDBox py={3} mb={20} height="65vh">
        <Grid container justifyContent="center" alignItems="center" sx={{ height: "100%", mt: 8 }}>
          <Grid item xs={12} lg={10}>
            <Formulario steps={steps} apiUrl={apiUrl} productId={id} />
          </Grid>
        </Grid>
      </MDBox>
      <Footer />
    </DashboardLayout>
  );
}

export default AltaInspeccion;
