-- ============================================================
-- Eventia – Script idempotente de creación / migración
-- Generado: 2026-03-13
-- Patrón:
--   1) CREATE TABLE IF NOT EXISTS  → crea si la tabla es nueva
--   2) ALTER TABLE ... ADD COLUMN IF NOT EXISTS → agrega columnas
--      faltantes si la tabla ya existía (seguro re-ejecutar N veces)
--   3) CREATE INDEX IF NOT EXISTS / CREATE UNIQUE INDEX IF NOT EXISTS
-- ============================================================


-- ============================================================
-- 01. PARAMÉTRICAS INDEPENDIENTES
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_idiomas (
    id_idioma   smallint     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      varchar(5)   NOT NULL,
    nombre      varchar(80)  NOT NULL,
    activo      boolean      NOT NULL DEFAULT true,
    fecha_alta  timestamptz  NOT NULL DEFAULT now(),
    fecha_modif timestamptz
);
ALTER TABLE public.ef_idiomas ADD COLUMN IF NOT EXISTS codigo      varchar(5)   NOT NULL DEFAULT '';
ALTER TABLE public.ef_idiomas ADD COLUMN IF NOT EXISTS nombre      varchar(80)  NOT NULL DEFAULT '';
ALTER TABLE public.ef_idiomas ADD COLUMN IF NOT EXISTS activo      boolean      NOT NULL DEFAULT true;
ALTER TABLE public.ef_idiomas ADD COLUMN IF NOT EXISTS fecha_alta  timestamptz  NOT NULL DEFAULT now();
ALTER TABLE public.ef_idiomas ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_tipos_evento (
    id_tipo_evento integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo         varchar(20)  NOT NULL,
    nombre         varchar(80)  NOT NULL,
    activo         boolean      NOT NULL DEFAULT true
);
ALTER TABLE public.ef_tipos_evento ADD COLUMN IF NOT EXISTS codigo varchar(20) NOT NULL DEFAULT '';
ALTER TABLE public.ef_tipos_evento ADD COLUMN IF NOT EXISTS nombre varchar(80) NOT NULL DEFAULT '';
ALTER TABLE public.ef_tipos_evento ADD COLUMN IF NOT EXISTS activo boolean     NOT NULL DEFAULT true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_dress_code (
    id_dress_code smallint    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        varchar(80) NOT NULL,
    activo        boolean     NOT NULL DEFAULT true
);
ALTER TABLE public.ef_dress_code ADD COLUMN IF NOT EXISTS nombre varchar(80) NOT NULL DEFAULT '';
ALTER TABLE public.ef_dress_code ADD COLUMN IF NOT EXISTS activo boolean     NOT NULL DEFAULT true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_roles (
    id_rol  integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  varchar(80)  NOT NULL,
    codigo  varchar(30)  NOT NULL
);
ALTER TABLE public.ef_roles ADD COLUMN IF NOT EXISTS nombre varchar(80) NOT NULL DEFAULT '';
ALTER TABLE public.ef_roles ADD COLUMN IF NOT EXISTS codigo varchar(30) NOT NULL DEFAULT '';

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_tramo_tipos (
    id_tramo_tipo smallint    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        varchar(80) NOT NULL,
    codigo        varchar(20) NOT NULL,
    activo        boolean     NOT NULL DEFAULT true
);
ALTER TABLE public.ef_tramo_tipos ADD COLUMN IF NOT EXISTS nombre varchar(80) NOT NULL DEFAULT '';
ALTER TABLE public.ef_tramo_tipos ADD COLUMN IF NOT EXISTS codigo varchar(20) NOT NULL DEFAULT '';
ALTER TABLE public.ef_tramo_tipos ADD COLUMN IF NOT EXISTS activo boolean     NOT NULL DEFAULT true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_param_entidades (
    id_entidad  integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      varchar(50)  NOT NULL,
    nombre      varchar(150) NOT NULL,
    activo      boolean      NOT NULL DEFAULT true,
    fecha_alta  timestamptz  NOT NULL DEFAULT now(),
    fecha_modif timestamptz
);
ALTER TABLE public.ef_param_entidades ADD COLUMN IF NOT EXISTS codigo      varchar(50)  NOT NULL DEFAULT '';
ALTER TABLE public.ef_param_entidades ADD COLUMN IF NOT EXISTS nombre      varchar(150) NOT NULL DEFAULT '';
ALTER TABLE public.ef_param_entidades ADD COLUMN IF NOT EXISTS activo      boolean      NOT NULL DEFAULT true;
ALTER TABLE public.ef_param_entidades ADD COLUMN IF NOT EXISTS fecha_alta  timestamptz  NOT NULL DEFAULT now();
ALTER TABLE public.ef_param_entidades ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_param_features (
    id_feature  integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      varchar(50)  NOT NULL,
    nombre      varchar(100) NOT NULL,
    descripcion varchar(300),
    tipo        char(1)      NOT NULL,
    activo      boolean      NOT NULL DEFAULT true
);
ALTER TABLE public.ef_param_features ADD COLUMN IF NOT EXISTS codigo      varchar(50)  NOT NULL DEFAULT '';
ALTER TABLE public.ef_param_features ADD COLUMN IF NOT EXISTS nombre      varchar(100) NOT NULL DEFAULT '';
ALTER TABLE public.ef_param_features ADD COLUMN IF NOT EXISTS descripcion varchar(300);
ALTER TABLE public.ef_param_features ADD COLUMN IF NOT EXISTS tipo        char(1)      NOT NULL DEFAULT 'B';
ALTER TABLE public.ef_param_features ADD COLUMN IF NOT EXISTS activo      boolean      NOT NULL DEFAULT true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_param_feature_dependencias (
    id_feature     integer NOT NULL,
    id_feature_dep integer NOT NULL,
    PRIMARY KEY (id_feature, id_feature_dep),
    CONSTRAINT fk_pfd_feature     FOREIGN KEY (id_feature)     REFERENCES public.ef_param_features(id_feature),
    CONSTRAINT fk_pfd_feature_dep FOREIGN KEY (id_feature_dep) REFERENCES public.ef_param_features(id_feature)
);

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_param_edad_rangos (
    id_param_edad_rango integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              varchar(80) NOT NULL,
    edad_min            smallint    NOT NULL,
    edad_max            smallint,
    activo              boolean     NOT NULL DEFAULT true,
    fecha_alta          timestamptz NOT NULL DEFAULT now(),
    fecha_modif         timestamptz,
    CONSTRAINT ck_per_edad_min CHECK (edad_min >= 0),
    CONSTRAINT ck_per_edad_max CHECK (edad_max IS NULL OR edad_max >= edad_min)
);
ALTER TABLE public.ef_param_edad_rangos ADD COLUMN IF NOT EXISTS nombre      varchar(80) NOT NULL DEFAULT '';
ALTER TABLE public.ef_param_edad_rangos ADD COLUMN IF NOT EXISTS edad_min    smallint    NOT NULL DEFAULT 0;
ALTER TABLE public.ef_param_edad_rangos ADD COLUMN IF NOT EXISTS edad_max    smallint;
ALTER TABLE public.ef_param_edad_rangos ADD COLUMN IF NOT EXISTS activo      boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_param_edad_rangos ADD COLUMN IF NOT EXISTS fecha_alta  timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.ef_param_edad_rangos ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_param_traducciones (
    id_traduccion integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_idioma     smallint     NOT NULL REFERENCES public.ef_idiomas(id_idioma),
    clave         varchar(100) NOT NULL,
    valor         varchar(500) NOT NULL,
    fecha_alta    timestamptz  NOT NULL DEFAULT now(),
    fecha_modif   timestamptz
);
ALTER TABLE public.ef_param_traducciones ADD COLUMN IF NOT EXISTS id_idioma   smallint     NOT NULL DEFAULT 0;
ALTER TABLE public.ef_param_traducciones ADD COLUMN IF NOT EXISTS clave       varchar(100) NOT NULL DEFAULT '';
ALTER TABLE public.ef_param_traducciones ADD COLUMN IF NOT EXISTS valor       varchar(500) NOT NULL DEFAULT '';
ALTER TABLE public.ef_param_traducciones ADD COLUMN IF NOT EXISTS fecha_alta  timestamptz  NOT NULL DEFAULT now();
ALTER TABLE public.ef_param_traducciones ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_param_restricciones_alimentarias (
    id_restriccion integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo         varchar(30)  NOT NULL,
    nombre         varchar(100) NOT NULL,
    descripcion    varchar(300),
    activo         boolean      NOT NULL DEFAULT true,
    fecha_alta     timestamptz  NOT NULL DEFAULT now(),
    fecha_modif    timestamptz
);
ALTER TABLE public.ef_param_restricciones_alimentarias ADD COLUMN IF NOT EXISTS codigo      varchar(30)  NOT NULL DEFAULT '';
ALTER TABLE public.ef_param_restricciones_alimentarias ADD COLUMN IF NOT EXISTS nombre      varchar(100) NOT NULL DEFAULT '';
ALTER TABLE public.ef_param_restricciones_alimentarias ADD COLUMN IF NOT EXISTS descripcion varchar(300);
ALTER TABLE public.ef_param_restricciones_alimentarias ADD COLUMN IF NOT EXISTS activo      boolean      NOT NULL DEFAULT true;
ALTER TABLE public.ef_param_restricciones_alimentarias ADD COLUMN IF NOT EXISTS fecha_alta  timestamptz  NOT NULL DEFAULT now();
ALTER TABLE public.ef_param_restricciones_alimentarias ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;


-- ============================================================
-- 02. PLANES, ADDONS, PRECIOS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_planes (
    id_plan     bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      varchar(30)  NOT NULL UNIQUE,
    nombre      varchar(100) NOT NULL,
    descripcion varchar(500),
    tipo        varchar(10)  NOT NULL,
    periodo     varchar(10)  NOT NULL,
    activo      boolean      NOT NULL DEFAULT true,
    config_json jsonb,
    fecha_alta  timestamptz  NOT NULL DEFAULT now(),
    fecha_modif timestamptz
);
ALTER TABLE public.ef_planes ADD COLUMN IF NOT EXISTS nombre      varchar(100) NOT NULL DEFAULT '';
ALTER TABLE public.ef_planes ADD COLUMN IF NOT EXISTS descripcion varchar(500);
ALTER TABLE public.ef_planes ADD COLUMN IF NOT EXISTS tipo        varchar(10)  NOT NULL DEFAULT 'B2C';
ALTER TABLE public.ef_planes ADD COLUMN IF NOT EXISTS periodo     varchar(10)  NOT NULL DEFAULT 'MENSUAL';
ALTER TABLE public.ef_planes ADD COLUMN IF NOT EXISTS activo      boolean      NOT NULL DEFAULT true;
ALTER TABLE public.ef_planes ADD COLUMN IF NOT EXISTS config_json jsonb;
ALTER TABLE public.ef_planes ADD COLUMN IF NOT EXISTS fecha_alta  timestamptz  NOT NULL DEFAULT now();
ALTER TABLE public.ef_planes ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_plan_features (
    id_plan_feature bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_plan         bigint  NOT NULL REFERENCES public.ef_planes(id_plan),
    id_feature      integer NOT NULL REFERENCES public.ef_param_features(id_feature),
    activo          boolean NOT NULL DEFAULT true
);
ALTER TABLE public.ef_plan_features ADD COLUMN IF NOT EXISTS activo boolean NOT NULL DEFAULT true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_plan_limites (
    id_plan_limite bigint   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_plan        bigint   NOT NULL REFERENCES public.ef_planes(id_plan),
    id_entidad     integer  NOT NULL REFERENCES public.ef_param_entidades(id_entidad),
    limite_valor   integer  NOT NULL DEFAULT 0
);
ALTER TABLE public.ef_plan_limites ADD COLUMN IF NOT EXISTS limite_valor integer NOT NULL DEFAULT 0;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_addons (
    id_addon    bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      varchar(30)  NOT NULL UNIQUE,
    nombre      varchar(100) NOT NULL,
    descripcion varchar(300),
    activo      boolean      NOT NULL DEFAULT true,
    fecha_alta  timestamptz  NOT NULL DEFAULT now(),
    fecha_modif timestamptz
);
ALTER TABLE public.ef_addons ADD COLUMN IF NOT EXISTS nombre      varchar(100) NOT NULL DEFAULT '';
ALTER TABLE public.ef_addons ADD COLUMN IF NOT EXISTS descripcion varchar(300);
ALTER TABLE public.ef_addons ADD COLUMN IF NOT EXISTS activo      boolean      NOT NULL DEFAULT true;
ALTER TABLE public.ef_addons ADD COLUMN IF NOT EXISTS fecha_alta  timestamptz  NOT NULL DEFAULT now();
ALTER TABLE public.ef_addons ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_addon_features (
    id_addon_feature bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_addon         bigint  NOT NULL REFERENCES public.ef_addons(id_addon),
    id_feature       integer NOT NULL REFERENCES public.ef_param_features(id_feature),
    activo           boolean NOT NULL DEFAULT true
);
ALTER TABLE public.ef_addon_features ADD COLUMN IF NOT EXISTS activo boolean NOT NULL DEFAULT true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_precios (
    id_precio   bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_plan     bigint         REFERENCES public.ef_planes(id_plan),
    id_addon    bigint         REFERENCES public.ef_addons(id_addon),
    moneda      varchar(5)     NOT NULL DEFAULT 'ARS',
    monto       numeric(12,2)  NOT NULL,
    activo      boolean        NOT NULL DEFAULT true,
    fecha_alta  timestamptz    NOT NULL DEFAULT now(),
    fecha_modif timestamptz
);
ALTER TABLE public.ef_precios ADD COLUMN IF NOT EXISTS id_addon    bigint;
ALTER TABLE public.ef_precios ADD COLUMN IF NOT EXISTS moneda      varchar(5)    NOT NULL DEFAULT 'ARS';
ALTER TABLE public.ef_precios ADD COLUMN IF NOT EXISTS monto       numeric(12,2) NOT NULL DEFAULT 0;
ALTER TABLE public.ef_precios ADD COLUMN IF NOT EXISTS activo      boolean       NOT NULL DEFAULT true;
ALTER TABLE public.ef_precios ADD COLUMN IF NOT EXISTS fecha_alta  timestamptz   NOT NULL DEFAULT now();
ALTER TABLE public.ef_precios ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;


-- ============================================================
-- 03. CUENTAS Y USUARIOS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_cuentas (
    id_cuenta   bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      varchar(150) NOT NULL,
    activo      boolean      NOT NULL DEFAULT true,
    fecha_alta  timestamptz  NOT NULL DEFAULT now(),
    fecha_modif timestamptz
);
ALTER TABLE public.ef_cuentas ADD COLUMN IF NOT EXISTS nombre      varchar(150) NOT NULL DEFAULT '';
ALTER TABLE public.ef_cuentas ADD COLUMN IF NOT EXISTS activo      boolean      NOT NULL DEFAULT true;
ALTER TABLE public.ef_cuentas ADD COLUMN IF NOT EXISTS fecha_alta  timestamptz  NOT NULL DEFAULT now();
ALTER TABLE public.ef_cuentas ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_usuarios (
    id_usuario       bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            varchar(320) NOT NULL UNIQUE,
    password_hash    varchar(255),
    nombre           varchar(80)  NOT NULL,
    apellido         varchar(80)  NOT NULL,
    email_verificado boolean      NOT NULL DEFAULT false,
    activo           boolean      NOT NULL DEFAULT true,
    auth_provider    varchar(20)  NOT NULL DEFAULT 'local',
    google_sub       varchar(50),
    avatar_url       varchar(500),
    fecha_alta       timestamptz  NOT NULL DEFAULT now(),
    fecha_modif      timestamptz
);
ALTER TABLE public.ef_usuarios ADD COLUMN IF NOT EXISTS password_hash    varchar(255);
ALTER TABLE public.ef_usuarios ADD COLUMN IF NOT EXISTS email_verificado boolean     NOT NULL DEFAULT false;
ALTER TABLE public.ef_usuarios ADD COLUMN IF NOT EXISTS activo           boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_usuarios ADD COLUMN IF NOT EXISTS auth_provider    varchar(20) NOT NULL DEFAULT 'local';
ALTER TABLE public.ef_usuarios ADD COLUMN IF NOT EXISTS google_sub       varchar(50);
ALTER TABLE public.ef_usuarios ADD COLUMN IF NOT EXISTS avatar_url       varchar(500);
ALTER TABLE public.ef_usuarios ADD COLUMN IF NOT EXISTS fecha_alta       timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.ef_usuarios ADD COLUMN IF NOT EXISTS fecha_modif      timestamptz;

CREATE UNIQUE INDEX IF NOT EXISTS ux_ef_usuarios_google_sub
    ON public.ef_usuarios (google_sub) WHERE google_sub IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_ef_usuarios_activo_true
    ON public.ef_usuarios (id_usuario) WHERE activo = true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_usuarios_roles (
    id_usuario_rol bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario     bigint  NOT NULL REFERENCES public.ef_usuarios(id_usuario),
    id_rol         integer NOT NULL REFERENCES public.ef_roles(id_rol),
    CONSTRAINT ux_ef_usuarios_roles UNIQUE (id_usuario, id_rol)
);

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_cuenta_usuarios (
    id_cuenta_usuario bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta         bigint      NOT NULL REFERENCES public.ef_cuentas(id_cuenta),
    id_usuario        bigint      NOT NULL REFERENCES public.ef_usuarios(id_usuario),
    activo            boolean     NOT NULL DEFAULT true,
    fecha_alta        timestamptz NOT NULL DEFAULT now(),
    fecha_modif       timestamptz,
    CONSTRAINT ux_cu UNIQUE (id_cuenta, id_usuario)
);
ALTER TABLE public.ef_cuenta_usuarios ADD COLUMN IF NOT EXISTS activo      boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_cuenta_usuarios ADD COLUMN IF NOT EXISTS fecha_alta  timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.ef_cuenta_usuarios ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_clientes (
    id_cliente     bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta      bigint       NOT NULL REFERENCES public.ef_cuentas(id_cuenta),
    nombre_cliente varchar(150) NOT NULL,
    email          varchar(200),
    telefono       varchar(50),
    notas          varchar(500),
    activo         boolean      NOT NULL DEFAULT true,
    fecha_alta     timestamptz  NOT NULL DEFAULT now(),
    fecha_modif    timestamptz
);
ALTER TABLE public.ef_clientes ADD COLUMN IF NOT EXISTS email          varchar(200);
ALTER TABLE public.ef_clientes ADD COLUMN IF NOT EXISTS telefono       varchar(50);
ALTER TABLE public.ef_clientes ADD COLUMN IF NOT EXISTS notas          varchar(500);
ALTER TABLE public.ef_clientes ADD COLUMN IF NOT EXISTS activo         boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_clientes ADD COLUMN IF NOT EXISTS fecha_alta     timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.ef_clientes ADD COLUMN IF NOT EXISTS fecha_modif    timestamptz;

CREATE INDEX IF NOT EXISTS ix_ef_clientes_id_cuenta ON public.ef_clientes (id_cuenta);


-- ============================================================
-- 04. PLANTILLAS DE EVENTO
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_plantillas_evento (
    id_plantilla bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       varchar(100) NOT NULL,
    descripcion  varchar(300),
    activo       boolean      NOT NULL DEFAULT true,
    fecha_alta   timestamptz  NOT NULL DEFAULT now(),
    fecha_modif  timestamptz
);
ALTER TABLE public.ef_plantillas_evento ADD COLUMN IF NOT EXISTS descripcion varchar(300);
ALTER TABLE public.ef_plantillas_evento ADD COLUMN IF NOT EXISTS activo      boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_plantillas_evento ADD COLUMN IF NOT EXISTS fecha_alta  timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.ef_plantillas_evento ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_plantilla_tramos (
    id_plantilla_tramo bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_plantilla       bigint      NOT NULL REFERENCES public.ef_plantillas_evento(id_plantilla),
    nombre             varchar(80) NOT NULL,
    leyenda_visible    varchar(200),
    orden              smallint    NOT NULL,
    activo             boolean     NOT NULL DEFAULT true
);
ALTER TABLE public.ef_plantilla_tramos ADD COLUMN IF NOT EXISTS leyenda_visible varchar(200);
ALTER TABLE public.ef_plantilla_tramos ADD COLUMN IF NOT EXISTS activo          boolean     NOT NULL DEFAULT true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_plantilla_accesos (
    id_plantilla_acceso bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_plantilla        bigint      NOT NULL REFERENCES public.ef_plantillas_evento(id_plantilla),
    nombre              varchar(80) NOT NULL,
    orden               smallint    NOT NULL
);

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_plantilla_acceso_tramos (
    id_plantilla_acceso bigint NOT NULL REFERENCES public.ef_plantilla_accesos(id_plantilla_acceso),
    id_plantilla_tramo  bigint NOT NULL REFERENCES public.ef_plantilla_tramos(id_plantilla_tramo),
    PRIMARY KEY (id_plantilla_acceso, id_plantilla_tramo)
);


-- ============================================================
-- 05. EVENTOS Y ESTRUCTURA
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_eventos (
    id_evento                    bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_evento               integer      NOT NULL REFERENCES public.ef_tipos_evento(id_tipo_evento),
    id_idioma                    smallint     NOT NULL REFERENCES public.ef_idiomas(id_idioma),
    id_cliente                   bigint       REFERENCES public.ef_clientes(id_cliente),
    id_dress_code                smallint     REFERENCES public.ef_dress_code(id_dress_code),
    id_plan                      bigint       REFERENCES public.ef_planes(id_plan),
    id_acceso_default            bigint,      -- FK diferida (self-referencing to ef_evento_accesos)
    anfitriones_texto            varchar(500) NOT NULL,
    dress_code_descripcion       varchar(200),
    saludo                       varchar(500),
    mensaje_bienvenida           varchar(500),
    notas                        varchar(500),
    estado                       char(1)      NOT NULL DEFAULT 'B',
    modo_acceso                  char(1)      NOT NULL DEFAULT 'I',
    modo_asistencia              char(1)      NOT NULL DEFAULT 'A',
    es_publico                   boolean      NOT NULL DEFAULT false,
    rsvp_public_token            varchar(64)  UNIQUE,
    id_usuario_rsvp_link_creator bigint       REFERENCES public.ef_usuarios(id_usuario),
    fecha_alta                   timestamptz  NOT NULL DEFAULT now(),
    fecha_modif                  timestamptz
);
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS id_cliente                   bigint;
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS id_dress_code                smallint;
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS id_plan                      bigint;
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS id_acceso_default            bigint;
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS dress_code_descripcion       varchar(200);
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS saludo                       varchar(500);
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS mensaje_bienvenida           varchar(500);
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS notas                        varchar(500);
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS modo_acceso                  char(1) NOT NULL DEFAULT 'I';
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS modo_asistencia              char(1) NOT NULL DEFAULT 'A';
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS es_publico                   boolean NOT NULL DEFAULT false;
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS rsvp_public_token            varchar(64);
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS id_usuario_rsvp_link_creator bigint;
ALTER TABLE public.ef_eventos ADD COLUMN IF NOT EXISTS fecha_modif                  timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_evento_usuarios (
    id_evento_usuario bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento         bigint      NOT NULL REFERENCES public.ef_eventos(id_evento),
    id_usuario        bigint      NOT NULL REFERENCES public.ef_usuarios(id_usuario),
    rol               varchar(20),
    activo            boolean     NOT NULL DEFAULT true,
    fecha_alta        timestamptz NOT NULL DEFAULT now(),
    fecha_modif       timestamptz,
    CONSTRAINT ux_eu UNIQUE (id_evento, id_usuario)
);
ALTER TABLE public.ef_evento_usuarios ADD COLUMN IF NOT EXISTS rol         varchar(20);
ALTER TABLE public.ef_evento_usuarios ADD COLUMN IF NOT EXISTS activo      boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_evento_usuarios ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_evento_estados_hist (
    id_hist    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento  bigint      NOT NULL REFERENCES public.ef_eventos(id_evento),
    estado     char(1)     NOT NULL,
    nota       varchar(300),
    id_usuario bigint      REFERENCES public.ef_usuarios(id_usuario),
    fecha_alta timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.ef_evento_estados_hist ADD COLUMN IF NOT EXISTS nota       varchar(300);
ALTER TABLE public.ef_evento_estados_hist ADD COLUMN IF NOT EXISTS id_usuario bigint;
CREATE INDEX IF NOT EXISTS ix_eeh_evento ON public.ef_evento_estados_hist (id_evento);

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_evento_links (
    id_evento_link bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento      bigint       NOT NULL REFERENCES public.ef_eventos(id_evento),
    titulo         varchar(100) NOT NULL,
    url            varchar(500) NOT NULL,
    orden          smallint     NOT NULL DEFAULT 1,
    activo         boolean      NOT NULL DEFAULT true,
    fecha_alta     timestamptz  NOT NULL DEFAULT now(),
    fecha_modif    timestamptz
);
ALTER TABLE public.ef_evento_links ADD COLUMN IF NOT EXISTS orden       smallint    NOT NULL DEFAULT 1;
ALTER TABLE public.ef_evento_links ADD COLUMN IF NOT EXISTS activo      boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_evento_links ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_evento_features (
    id_evento_feature bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento         bigint  NOT NULL REFERENCES public.ef_eventos(id_evento),
    id_feature        integer NOT NULL REFERENCES public.ef_param_features(id_feature),
    activo            boolean NOT NULL DEFAULT true,
    CONSTRAINT ux_ef UNIQUE (id_evento, id_feature)
);
ALTER TABLE public.ef_evento_features ADD COLUMN IF NOT EXISTS activo boolean NOT NULL DEFAULT true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_solicitudes_plantilla (
    id_solicitud bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento    bigint      NOT NULL REFERENCES public.ef_eventos(id_evento),
    id_plantilla bigint      NOT NULL REFERENCES public.ef_plantillas_evento(id_plantilla),
    estado       char(1)     NOT NULL DEFAULT 'P',
    fecha_alta   timestamptz NOT NULL DEFAULT now(),
    fecha_modif  timestamptz
);
ALTER TABLE public.ef_solicitudes_plantilla ADD COLUMN IF NOT EXISTS estado      char(1)     NOT NULL DEFAULT 'P';
ALTER TABLE public.ef_solicitudes_plantilla ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;


-- ============================================================
-- 06. TRAMOS Y ACCESOS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_evento_tramos (
    id_tramo          bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento         bigint         NOT NULL REFERENCES public.ef_eventos(id_evento) ON DELETE CASCADE,
    id_tramo_tipo     smallint       REFERENCES public.ef_tramo_tipos(id_tramo_tipo),
    nombre            varchar(80)    NOT NULL,
    leyenda_visible   varchar(200),
    notas_internas    varchar(500),
    fecha_hora_inicio timestamptz    NOT NULL,
    fecha_hora_fin    timestamptz,
    lugar             varchar(200),
    direccion         varchar(200),
    latitud           numeric(9,6),
    longitud          numeric(9,6),
    orden             smallint       NOT NULL,
    cupo              integer,
    activo            boolean        NOT NULL DEFAULT true,
    fecha_alta        timestamptz    NOT NULL DEFAULT now(),
    fecha_modif       timestamptz,
    CONSTRAINT ux_et_evento_orden UNIQUE (id_evento, orden)
);
ALTER TABLE public.ef_evento_tramos ADD COLUMN IF NOT EXISTS id_tramo_tipo     smallint;
ALTER TABLE public.ef_evento_tramos ADD COLUMN IF NOT EXISTS leyenda_visible   varchar(200);
ALTER TABLE public.ef_evento_tramos ADD COLUMN IF NOT EXISTS notas_internas    varchar(500);
ALTER TABLE public.ef_evento_tramos ADD COLUMN IF NOT EXISTS fecha_hora_fin    timestamptz;
ALTER TABLE public.ef_evento_tramos ADD COLUMN IF NOT EXISTS lugar             varchar(200);
ALTER TABLE public.ef_evento_tramos ADD COLUMN IF NOT EXISTS direccion         varchar(200);
ALTER TABLE public.ef_evento_tramos ADD COLUMN IF NOT EXISTS latitud           numeric(9,6);
ALTER TABLE public.ef_evento_tramos ADD COLUMN IF NOT EXISTS longitud          numeric(9,6);
ALTER TABLE public.ef_evento_tramos ADD COLUMN IF NOT EXISTS cupo              integer;
ALTER TABLE public.ef_evento_tramos ADD COLUMN IF NOT EXISTS activo            boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_evento_tramos ADD COLUMN IF NOT EXISTS fecha_alta        timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.ef_evento_tramos ADD COLUMN IF NOT EXISTS fecha_modif       timestamptz;
CREATE INDEX IF NOT EXISTS ix_et_evento ON public.ef_evento_tramos (id_evento);

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_evento_accesos (
    id_acceso    bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento    bigint        NOT NULL REFERENCES public.ef_eventos(id_evento),
    nombre       varchar(120)  NOT NULL,
    mensaje_rsvp varchar(300),
    es_publico   boolean       NOT NULL DEFAULT false,
    cupo         integer,
    precio       numeric(12,2),
    activo       boolean       NOT NULL DEFAULT true,
    orden        smallint      NOT NULL DEFAULT 1,
    fecha_alta   timestamptz   NOT NULL DEFAULT now(),
    fecha_modif  timestamptz
);
ALTER TABLE public.ef_evento_accesos ADD COLUMN IF NOT EXISTS mensaje_rsvp varchar(300);
ALTER TABLE public.ef_evento_accesos ADD COLUMN IF NOT EXISTS es_publico   boolean      NOT NULL DEFAULT false;
ALTER TABLE public.ef_evento_accesos ADD COLUMN IF NOT EXISTS cupo         integer;
ALTER TABLE public.ef_evento_accesos ADD COLUMN IF NOT EXISTS precio       numeric(12,2);
ALTER TABLE public.ef_evento_accesos ADD COLUMN IF NOT EXISTS activo       boolean      NOT NULL DEFAULT true;
ALTER TABLE public.ef_evento_accesos ADD COLUMN IF NOT EXISTS orden        smallint     NOT NULL DEFAULT 1;
ALTER TABLE public.ef_evento_accesos ADD COLUMN IF NOT EXISTS fecha_alta   timestamptz  NOT NULL DEFAULT now();
ALTER TABLE public.ef_evento_accesos ADD COLUMN IF NOT EXISTS fecha_modif  timestamptz;
CREATE INDEX IF NOT EXISTS ix_ea_evento ON public.ef_evento_accesos (id_evento);

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_evento_acceso_tramos (
    id_acceso bigint NOT NULL REFERENCES public.ef_evento_accesos(id_acceso),
    id_tramo  bigint NOT NULL REFERENCES public.ef_evento_tramos(id_tramo),
    PRIMARY KEY (id_acceso, id_tramo)
);

-- FK diferida: ef_eventos.id_acceso_default → ef_evento_accesos
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_schema = 'public'
          AND table_name   = 'ef_eventos'
          AND constraint_name = 'fk_eventos_acceso_default'
    ) THEN
        ALTER TABLE public.ef_eventos
            ADD CONSTRAINT fk_eventos_acceso_default
            FOREIGN KEY (id_acceso_default)
            REFERENCES public.ef_evento_accesos(id_acceso)
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END$$;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_evento_edad_rangos (
    id_evento_edad_rango bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento            bigint      NOT NULL REFERENCES public.ef_eventos(id_evento),
    id_param_edad_rango  integer     REFERENCES public.ef_param_edad_rangos(id_param_edad_rango),
    nombre               varchar(80),
    edad_min             smallint    NOT NULL,
    edad_max             smallint,
    activo               boolean     NOT NULL DEFAULT true,
    fecha_alta           timestamptz NOT NULL DEFAULT now(),
    fecha_modif          timestamptz,
    CONSTRAINT ck_eeer_edad CHECK (edad_max IS NULL OR edad_max >= edad_min)
);
ALTER TABLE public.ef_evento_edad_rangos ADD COLUMN IF NOT EXISTS id_param_edad_rango integer;
ALTER TABLE public.ef_evento_edad_rangos ADD COLUMN IF NOT EXISTS nombre              varchar(80);
ALTER TABLE public.ef_evento_edad_rangos ADD COLUMN IF NOT EXISTS edad_max            smallint;
ALTER TABLE public.ef_evento_edad_rangos ADD COLUMN IF NOT EXISTS activo              boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_evento_edad_rangos ADD COLUMN IF NOT EXISTS fecha_alta          timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.ef_evento_edad_rangos ADD COLUMN IF NOT EXISTS fecha_modif         timestamptz;


-- ============================================================
-- 07. LINKS DE ACCESO GENÉRICOS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_evento_acceso_links (
    id_acceso_link     bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_acceso          bigint       NOT NULL REFERENCES public.ef_evento_accesos(id_acceso),
    id_evento          bigint       NOT NULL REFERENCES public.ef_eventos(id_evento),
    id_usuario_creador bigint       REFERENCES public.ef_usuarios(id_usuario),
    titulo             varchar(60)  NOT NULL,
    leyenda_publica    varchar(200),
    token              varchar(64)  NOT NULL UNIQUE,
    max_personas_total integer      NOT NULL,
    max_adultos        integer,
    activo             boolean      NOT NULL DEFAULT true,
    fecha_expiracion   timestamptz,
    fecha_alta         timestamptz  NOT NULL DEFAULT now(),
    fecha_modif        timestamptz,
    CONSTRAINT ck_eal_max_adultos  CHECK (max_adultos IS NULL OR max_adultos >= 0),
    CONSTRAINT ck_eal_max_personas CHECK (max_personas_total >= 1)
);
ALTER TABLE public.ef_evento_acceso_links ADD COLUMN IF NOT EXISTS id_usuario_creador bigint;
ALTER TABLE public.ef_evento_acceso_links ADD COLUMN IF NOT EXISTS leyenda_publica    varchar(200);
ALTER TABLE public.ef_evento_acceso_links ADD COLUMN IF NOT EXISTS max_adultos        integer;
ALTER TABLE public.ef_evento_acceso_links ADD COLUMN IF NOT EXISTS fecha_expiracion   timestamptz;
ALTER TABLE public.ef_evento_acceso_links ADD COLUMN IF NOT EXISTS fecha_modif        timestamptz;
CREATE INDEX IF NOT EXISTS ix_eal_acceso ON public.ef_evento_acceso_links (id_acceso);
CREATE INDEX IF NOT EXISTS ix_eal_activo ON public.ef_evento_acceso_links (activo);


-- ============================================================
-- 08. GRUPOS RSVP E INVITADOS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_rsvp_grupos (
    id_rsvp_grupo           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento               bigint       NOT NULL REFERENCES public.ef_eventos(id_evento),
    id_acceso               bigint       NOT NULL REFERENCES public.ef_evento_accesos(id_acceso),
    id_acceso_link          bigint       REFERENCES public.ef_evento_acceso_links(id_acceso_link),  -- nullable
    nombre_grupo            varchar(200) NOT NULL,
    max_personas_total      integer      NOT NULL,
    max_adultos             integer,
    cantidad_total          integer      NOT NULL,
    cant_adultos_sin_nombre integer      NOT NULL DEFAULT 0,
    cant_menores_sin_nombre integer      NOT NULL DEFAULT 0,
    rsvp_estado             char(1)      NOT NULL DEFAULT 'P',
    rsvp_mensaje            varchar(300),
    fecha_rsvp              timestamptz,
    activo                  boolean      NOT NULL DEFAULT true,
    fecha_alta              timestamptz  NOT NULL DEFAULT now(),
    fecha_modif             timestamptz,
    CONSTRAINT ck_rg_max_personas            CHECK (max_personas_total >= 1),
    CONSTRAINT ck_rg_rsvp_estado             CHECK (rsvp_estado IN ('P','Y','N')),
    CONSTRAINT ck_rg_cantidad_total          CHECK (cantidad_total >= 1 AND cantidad_total <= max_personas_total),
    CONSTRAINT ck_rg_cant_adultos_sin_nombre CHECK (cant_adultos_sin_nombre >= 0),
    CONSTRAINT ck_rg_cant_menores_sin_nombre CHECK (cant_menores_sin_nombre >= 0)
);
-- Columnas que pueden faltar en instalaciones anteriores:
ALTER TABLE public.ef_rsvp_grupos ALTER COLUMN id_acceso_link DROP NOT NULL;   -- permitir NULL
ALTER TABLE public.ef_rsvp_grupos ADD COLUMN IF NOT EXISTS nombre_grupo            varchar(200) NOT NULL DEFAULT '';
ALTER TABLE public.ef_rsvp_grupos ADD COLUMN IF NOT EXISTS max_adultos             integer;
ALTER TABLE public.ef_rsvp_grupos ADD COLUMN IF NOT EXISTS cant_adultos_sin_nombre integer NOT NULL DEFAULT 0;
ALTER TABLE public.ef_rsvp_grupos ADD COLUMN IF NOT EXISTS cant_menores_sin_nombre integer NOT NULL DEFAULT 0;
ALTER TABLE public.ef_rsvp_grupos ADD COLUMN IF NOT EXISTS rsvp_mensaje            varchar(300);
ALTER TABLE public.ef_rsvp_grupos ADD COLUMN IF NOT EXISTS fecha_rsvp              timestamptz;
ALTER TABLE public.ef_rsvp_grupos ADD COLUMN IF NOT EXISTS fecha_modif             timestamptz;
-- Check constraints (si no existen):
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='ck_rg_cant_adultos_sin_nombre') THEN
    ALTER TABLE public.ef_rsvp_grupos ADD CONSTRAINT ck_rg_cant_adultos_sin_nombre CHECK (cant_adultos_sin_nombre >= 0);
END IF; END$$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='ck_rg_cant_menores_sin_nombre') THEN
    ALTER TABLE public.ef_rsvp_grupos ADD CONSTRAINT ck_rg_cant_menores_sin_nombre CHECK (cant_menores_sin_nombre >= 0);
END IF; END$$;

CREATE INDEX IF NOT EXISTS ix_rg_evento        ON public.ef_rsvp_grupos (id_evento);
CREATE INDEX IF NOT EXISTS ix_rg_link          ON public.ef_rsvp_grupos (id_acceso_link);
CREATE INDEX IF NOT EXISTS ix_rg_evento_estado ON public.ef_rsvp_grupos (id_evento, rsvp_estado);

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_invitados (
    id_invitado          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento            bigint       NOT NULL REFERENCES public.ef_eventos(id_evento),
    id_acceso            bigint       REFERENCES public.ef_evento_accesos(id_acceso),
    id_rsvp_grupo        bigint       REFERENCES public.ef_rsvp_grupos(id_rsvp_grupo),
    id_usuario_invitador bigint       REFERENCES public.ef_usuarios(id_usuario),
    nombre               varchar(80)  NOT NULL,
    apellido             varchar(80)  NOT NULL,
    sobrenombre          varchar(80),
    email                varchar(200),
    celular              varchar(50),
    rsvp_token           varchar(64),  -- nullable: solo el titular tiene token
    qr_token             varchar(64),
    rsvp_estado          char(1)      NOT NULL DEFAULT 'P',
    rsvp_mensaje         varchar(300),
    fecha_rsvp           timestamptz,
    es_titular_grupo     boolean      NOT NULL DEFAULT false,
    activo               boolean      NOT NULL DEFAULT true,
    fecha_alta           timestamptz  NOT NULL DEFAULT now(),
    fecha_modif          timestamptz,
    CONSTRAINT ck_inv_rsvp_estado CHECK (rsvp_estado IN ('P','Y','N'))
);
ALTER TABLE public.ef_invitados ADD COLUMN IF NOT EXISTS id_acceso            bigint;
ALTER TABLE public.ef_invitados ADD COLUMN IF NOT EXISTS id_rsvp_grupo        bigint;
ALTER TABLE public.ef_invitados ADD COLUMN IF NOT EXISTS id_usuario_invitador bigint;
ALTER TABLE public.ef_invitados ADD COLUMN IF NOT EXISTS sobrenombre          varchar(80);
ALTER TABLE public.ef_invitados ADD COLUMN IF NOT EXISTS email                varchar(200);
ALTER TABLE public.ef_invitados ADD COLUMN IF NOT EXISTS celular              varchar(50);
ALTER TABLE public.ef_invitados ADD COLUMN IF NOT EXISTS qr_token             varchar(64);
ALTER TABLE public.ef_invitados ADD COLUMN IF NOT EXISTS rsvp_mensaje         varchar(300);
ALTER TABLE public.ef_invitados ADD COLUMN IF NOT EXISTS fecha_rsvp           timestamptz;
ALTER TABLE public.ef_invitados ADD COLUMN IF NOT EXISTS es_titular_grupo     boolean NOT NULL DEFAULT false;
ALTER TABLE public.ef_invitados ADD COLUMN IF NOT EXISTS fecha_modif          timestamptz;
-- rsvp_token: hacer nullable si estaba NOT NULL
ALTER TABLE public.ef_invitados ALTER COLUMN rsvp_token DROP NOT NULL;

-- Índice qr_token corregido (parcial: solo cuando no es null)
DROP INDEX IF EXISTS public.ux_ef_invitados_qr_token;
CREATE UNIQUE INDEX IF NOT EXISTS ux_ef_invitados_qr_token
    ON public.ef_invitados (qr_token) WHERE qr_token IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_ef_invitados_rsvp_token
    ON public.ef_invitados (rsvp_token) WHERE rsvp_token IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_inv_evento ON public.ef_invitados (id_evento);
CREATE INDEX IF NOT EXISTS ix_inv_grupo  ON public.ef_invitados (id_rsvp_grupo);

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_rsvp_grupo_integrantes (
    id_rsvp_grupo_integrante bigint   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rsvp_grupo            bigint   NOT NULL REFERENCES public.ef_rsvp_grupos(id_rsvp_grupo),
    id_invitado              bigint   NOT NULL REFERENCES public.ef_invitados(id_invitado),
    id_evento_edad_rango     bigint   REFERENCES public.ef_evento_edad_rangos(id_evento_edad_rango),
    rol                      char(1)  NOT NULL,              -- T=titular, A=acompañante
    orden                    integer  NOT NULL DEFAULT 1,
    rol_evento               char(1)  NOT NULL DEFAULT 'A',  -- A=adulto, N=niño, R=responsable
    asiste                   char(1)  NOT NULL DEFAULT 'P',  -- P=pendiente, Y=sí, N=no
    edad_anios               smallint,
    requiere_asistencia      boolean  NOT NULL DEFAULT false,
    alimentacion_detalle     varchar(200),
    fecha_respuesta          timestamptz,
    CONSTRAINT ux_rgi_invitado   UNIQUE (id_invitado),
    CONSTRAINT ck_rgi_orden      CHECK  (orden >= 1),
    CONSTRAINT ck_rgi_rol        CHECK  (rol IN ('T','A')),
    CONSTRAINT ck_rgi_rol_evento CHECK  (rol_evento IN ('A','N','R')),
    CONSTRAINT ck_rgi_asiste     CHECK  (asiste IN ('P','Y','N')),
    CONSTRAINT ck_rgi_edad_anios CHECK  (edad_anios IS NULL OR (edad_anios >= 0 AND edad_anios <= 120))
);
ALTER TABLE public.ef_rsvp_grupo_integrantes ADD COLUMN IF NOT EXISTS id_evento_edad_rango  bigint;
ALTER TABLE public.ef_rsvp_grupo_integrantes ADD COLUMN IF NOT EXISTS rol_evento             char(1) NOT NULL DEFAULT 'A';
ALTER TABLE public.ef_rsvp_grupo_integrantes ADD COLUMN IF NOT EXISTS asiste                char(1) NOT NULL DEFAULT 'P';
ALTER TABLE public.ef_rsvp_grupo_integrantes ADD COLUMN IF NOT EXISTS edad_anios            smallint;
ALTER TABLE public.ef_rsvp_grupo_integrantes ADD COLUMN IF NOT EXISTS requiere_asistencia   boolean NOT NULL DEFAULT false;
ALTER TABLE public.ef_rsvp_grupo_integrantes ADD COLUMN IF NOT EXISTS alimentacion_detalle  varchar(200);
ALTER TABLE public.ef_rsvp_grupo_integrantes ADD COLUMN IF NOT EXISTS fecha_respuesta       timestamptz;
-- Check constraint asiste (si no existe):
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='ck_rgi_asiste') THEN
    ALTER TABLE public.ef_rsvp_grupo_integrantes ADD CONSTRAINT ck_rgi_asiste CHECK (asiste IN ('P','Y','N'));
END IF; END$$;

CREATE UNIQUE INDEX IF NOT EXISTS ux_rgi_un_titular_por_grupo
    ON public.ef_rsvp_grupo_integrantes (id_rsvp_grupo) WHERE rol = 'T';
CREATE INDEX IF NOT EXISTS ix_rgi_grupo       ON public.ef_rsvp_grupo_integrantes (id_rsvp_grupo);
CREATE INDEX IF NOT EXISTS ix_rgi_evento_edad ON public.ef_rsvp_grupo_integrantes (id_evento_edad_rango);

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_rsvp_integrante_restricciones (
    id_rsvp_grupo_integrante bigint  NOT NULL REFERENCES public.ef_rsvp_grupo_integrantes(id_rsvp_grupo_integrante),
    id_restriccion           integer NOT NULL REFERENCES public.ef_param_restricciones_alimentarias(id_restriccion),
    detalle                  varchar(200),
    PRIMARY KEY (id_rsvp_grupo_integrante, id_restriccion)
);
ALTER TABLE public.ef_rsvp_integrante_restricciones ADD COLUMN IF NOT EXISTS detalle varchar(200);


-- ============================================================
-- 09. QR SCANS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_qr_scans (
    id_qr_scan  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_invitado bigint      NOT NULL REFERENCES public.ef_invitados(id_invitado),
    id_evento   bigint      NOT NULL REFERENCES public.ef_eventos(id_evento),
    id_tramo    bigint      REFERENCES public.ef_evento_tramos(id_tramo),
    id_usuario  bigint      REFERENCES public.ef_usuarios(id_usuario),
    resultado   char(1)     NOT NULL,
    detalle     varchar(200),
    fecha_scan  timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.ef_qr_scans ADD COLUMN IF NOT EXISTS id_tramo  bigint;
ALTER TABLE public.ef_qr_scans ADD COLUMN IF NOT EXISTS id_usuario bigint;
ALTER TABLE public.ef_qr_scans ADD COLUMN IF NOT EXISTS detalle   varchar(200);
CREATE INDEX IF NOT EXISTS ix_qrs_invitado ON public.ef_qr_scans (id_invitado);
CREATE INDEX IF NOT EXISTS ix_qrs_evento   ON public.ef_qr_scans (id_evento);


-- ============================================================
-- 10. AUTORIZACIONES
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_autorizaciones (
    id_autorizacion bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento       bigint      NOT NULL REFERENCES public.ef_eventos(id_evento),
    id_usuario      bigint      NOT NULL REFERENCES public.ef_usuarios(id_usuario),
    id_rol          integer     NOT NULL REFERENCES public.ef_roles(id_rol),
    activo          boolean     NOT NULL DEFAULT true,
    fecha_alta      timestamptz NOT NULL DEFAULT now(),
    fecha_modif     timestamptz,
    CONSTRAINT ux_aut UNIQUE (id_evento, id_usuario, id_rol)
);
ALTER TABLE public.ef_autorizaciones ADD COLUMN IF NOT EXISTS activo      boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_autorizaciones ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;


-- ============================================================
-- 11. MÚSICA
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_evento_musica_momentos (
    id_momento bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento  bigint       NOT NULL REFERENCES public.ef_eventos(id_evento),
    nombre     varchar(100) NOT NULL,
    orden      smallint     NOT NULL DEFAULT 1,
    activo     boolean      NOT NULL DEFAULT true
);
ALTER TABLE public.ef_evento_musica_momentos ADD COLUMN IF NOT EXISTS orden  smallint NOT NULL DEFAULT 1;
ALTER TABLE public.ef_evento_musica_momentos ADD COLUMN IF NOT EXISTS activo boolean  NOT NULL DEFAULT true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_evento_musica_playlist (
    id_playlist bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_momento  bigint       NOT NULL REFERENCES public.ef_evento_musica_momentos(id_momento),
    titulo      varchar(200) NOT NULL,
    artista     varchar(200),
    url         varchar(500),
    activo      boolean      NOT NULL DEFAULT true,
    fecha_alta  timestamptz  NOT NULL DEFAULT now()
);
ALTER TABLE public.ef_evento_musica_playlist ADD COLUMN IF NOT EXISTS artista varchar(200);
ALTER TABLE public.ef_evento_musica_playlist ADD COLUMN IF NOT EXISTS url     varchar(500);
ALTER TABLE public.ef_evento_musica_playlist ADD COLUMN IF NOT EXISTS activo  boolean     NOT NULL DEFAULT true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_evento_musica_sugerencias_estado (
    id_evento  bigint  NOT NULL REFERENCES public.ef_eventos(id_evento),
    id_momento bigint  NOT NULL REFERENCES public.ef_evento_musica_momentos(id_momento),
    aceptando  boolean NOT NULL DEFAULT true,
    PRIMARY KEY (id_evento, id_momento)
);
ALTER TABLE public.ef_evento_musica_sugerencias_estado ADD COLUMN IF NOT EXISTS aceptando boolean NOT NULL DEFAULT true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_evento_musica_bloqueos (
    id_bloqueo bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento  bigint       NOT NULL REFERENCES public.ef_eventos(id_evento),
    termino    varchar(100) NOT NULL,
    activo     boolean      NOT NULL DEFAULT true,
    fecha_alta timestamptz  NOT NULL DEFAULT now()
);
ALTER TABLE public.ef_evento_musica_bloqueos ADD COLUMN IF NOT EXISTS activo boolean NOT NULL DEFAULT true;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_invitado_musica_sugerencias (
    id_sugerencia bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_invitado   bigint       NOT NULL REFERENCES public.ef_invitados(id_invitado),
    id_momento    bigint       NOT NULL REFERENCES public.ef_evento_musica_momentos(id_momento),
    titulo        varchar(200) NOT NULL,
    artista       varchar(200),
    url           varchar(500),
    estado        char(1)      NOT NULL DEFAULT 'P',
    fecha_alta    timestamptz  NOT NULL DEFAULT now(),
    fecha_modif   timestamptz
);
ALTER TABLE public.ef_invitado_musica_sugerencias ADD COLUMN IF NOT EXISTS artista     varchar(200);
ALTER TABLE public.ef_invitado_musica_sugerencias ADD COLUMN IF NOT EXISTS url         varchar(500);
ALTER TABLE public.ef_invitado_musica_sugerencias ADD COLUMN IF NOT EXISTS estado      char(1)     NOT NULL DEFAULT 'P';
ALTER TABLE public.ef_invitado_musica_sugerencias ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_invitado_musica_votos (
    id_voto       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_invitado   bigint NOT NULL REFERENCES public.ef_invitados(id_invitado),
    id_sugerencia bigint NOT NULL REFERENCES public.ef_invitado_musica_sugerencias(id_sugerencia),
    CONSTRAINT ux_voto UNIQUE (id_invitado, id_sugerencia)
);


-- ============================================================
-- 12. SUSCRIPCIONES Y PAGOS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_suscripciones (
    id_suscripcion bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta      bigint      NOT NULL REFERENCES public.ef_cuentas(id_cuenta),
    id_plan        bigint      NOT NULL REFERENCES public.ef_planes(id_plan),
    estado         char(1)     NOT NULL DEFAULT 'A',
    fecha_inicio   timestamptz NOT NULL,
    fecha_fin      timestamptz,
    activo         boolean     NOT NULL DEFAULT true,
    fecha_alta     timestamptz NOT NULL DEFAULT now(),
    fecha_modif    timestamptz
);
ALTER TABLE public.ef_suscripciones ADD COLUMN IF NOT EXISTS fecha_fin   timestamptz;
ALTER TABLE public.ef_suscripciones ADD COLUMN IF NOT EXISTS activo      boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_suscripciones ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_pagos (
    id_pago        bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_suscripcion bigint        REFERENCES public.ef_suscripciones(id_suscripcion),
    id_cuenta      bigint        NOT NULL REFERENCES public.ef_cuentas(id_cuenta),
    monto          numeric(12,2) NOT NULL,
    moneda         varchar(5)    NOT NULL DEFAULT 'ARS',
    estado         char(1)       NOT NULL DEFAULT 'P',
    medio_pago     varchar(30),
    referencia_ext varchar(100),
    descripcion    varchar(300),
    fecha_pago     timestamptz,
    fecha_alta     timestamptz   NOT NULL DEFAULT now(),
    fecha_modif    timestamptz
);
ALTER TABLE public.ef_pagos ADD COLUMN IF NOT EXISTS id_suscripcion bigint;
ALTER TABLE public.ef_pagos ADD COLUMN IF NOT EXISTS medio_pago     varchar(30);
ALTER TABLE public.ef_pagos ADD COLUMN IF NOT EXISTS referencia_ext varchar(100);
ALTER TABLE public.ef_pagos ADD COLUMN IF NOT EXISTS descripcion    varchar(300);
ALTER TABLE public.ef_pagos ADD COLUMN IF NOT EXISTS fecha_pago     timestamptz;
ALTER TABLE public.ef_pagos ADD COLUMN IF NOT EXISTS fecha_modif    timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_retiros (
    id_retiro      bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta      bigint        NOT NULL REFERENCES public.ef_cuentas(id_cuenta),
    monto          numeric(12,2) NOT NULL,
    moneda         varchar(5)    NOT NULL DEFAULT 'ARS',
    estado         char(1)       NOT NULL DEFAULT 'P',
    referencia_ext varchar(100),
    descripcion    varchar(300),
    fecha_retiro   timestamptz,
    fecha_alta     timestamptz   NOT NULL DEFAULT now(),
    fecha_modif    timestamptz
);
ALTER TABLE public.ef_retiros ADD COLUMN IF NOT EXISTS referencia_ext varchar(100);
ALTER TABLE public.ef_retiros ADD COLUMN IF NOT EXISTS descripcion    varchar(300);
ALTER TABLE public.ef_retiros ADD COLUMN IF NOT EXISTS fecha_retiro   timestamptz;
ALTER TABLE public.ef_retiros ADD COLUMN IF NOT EXISTS fecha_modif    timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_scope_addons (
    id_scope_addon bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta      bigint      NOT NULL REFERENCES public.ef_cuentas(id_cuenta),
    id_addon       bigint      NOT NULL REFERENCES public.ef_addons(id_addon),
    activo         boolean     NOT NULL DEFAULT true,
    fecha_alta     timestamptz NOT NULL DEFAULT now(),
    fecha_modif    timestamptz,
    CONSTRAINT ux_sa UNIQUE (id_cuenta, id_addon)
);
ALTER TABLE public.ef_scope_addons ADD COLUMN IF NOT EXISTS activo      boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_scope_addons ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_webhook_eventos (
    id_webhook  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo        varchar(60) NOT NULL,
    payload     jsonb,
    estado      char(1)     NOT NULL DEFAULT 'P',
    intentos    smallint    NOT NULL DEFAULT 0,
    fecha_alta  timestamptz NOT NULL DEFAULT now(),
    fecha_modif timestamptz
);
ALTER TABLE public.ef_webhook_eventos ADD COLUMN IF NOT EXISTS payload     jsonb;
ALTER TABLE public.ef_webhook_eventos ADD COLUMN IF NOT EXISTS intentos    smallint    NOT NULL DEFAULT 0;
ALTER TABLE public.ef_webhook_eventos ADD COLUMN IF NOT EXISTS fecha_modif timestamptz;


-- ============================================================
-- 13. B2B PROSPECTOS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ef_b2b_prospectos (
    id_prospecto    bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razon_social    varchar(200),
    nombre_contacto varchar(150)  NOT NULL,
    email           varchar(320),
    telefono        varchar(50),
    estado          char(1)       NOT NULL DEFAULT 'N',
    notas           varchar(2000),
    activo          boolean       NOT NULL DEFAULT true,
    id_usuario      bigint        REFERENCES public.ef_usuarios(id_usuario),
    fecha_alta      timestamptz   NOT NULL DEFAULT now(),
    fecha_modif     timestamptz
);
ALTER TABLE public.ef_b2b_prospectos ADD COLUMN IF NOT EXISTS razon_social varchar(200);
ALTER TABLE public.ef_b2b_prospectos ADD COLUMN IF NOT EXISTS email        varchar(320);
ALTER TABLE public.ef_b2b_prospectos ADD COLUMN IF NOT EXISTS telefono     varchar(50);
ALTER TABLE public.ef_b2b_prospectos ADD COLUMN IF NOT EXISTS notas        varchar(2000);
ALTER TABLE public.ef_b2b_prospectos ADD COLUMN IF NOT EXISTS activo       boolean     NOT NULL DEFAULT true;
ALTER TABLE public.ef_b2b_prospectos ADD COLUMN IF NOT EXISTS id_usuario   bigint;
ALTER TABLE public.ef_b2b_prospectos ADD COLUMN IF NOT EXISTS fecha_modif  timestamptz;

-- ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ef_b2b_prospectos_hist (
    id_hist      bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_prospecto bigint        NOT NULL REFERENCES public.ef_b2b_prospectos(id_prospecto),
    estado       char(1)       NOT NULL,
    nota         varchar(1000),
    id_usuario   bigint        REFERENCES public.ef_usuarios(id_usuario),
    fecha_alta   timestamptz   NOT NULL DEFAULT now()
);
ALTER TABLE public.ef_b2b_prospectos_hist ADD COLUMN IF NOT EXISTS nota       varchar(1000);
ALTER TABLE public.ef_b2b_prospectos_hist ADD COLUMN IF NOT EXISTS id_usuario bigint;
CREATE INDEX IF NOT EXISTS ix_bph_prospecto ON public.ef_b2b_prospectos_hist (id_prospecto);


-- ============================================================
-- FIN DEL SCRIPT
-- ============================================================
