
import re

file_path = r'c:\Desarrollo\Eventia\CodigoFuente\antenas\API\MIGRACION_EVENTIA_POSTGRES.sql'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Extract table definitions
# Matches: CREATE TABLE IF NOT EXISTS public.tablename ( columns )
table_pattern = re.compile(r'CREATE TABLE IF NOT EXISTS public\.(ef_\w+)\s*\((.*?)\);', re.DOTALL)
tables = table_pattern.findall(content)

tables_to_sync = [
    'ef_b2b_prospectos',
    'ef_b2b_prospectos_hist',
    'ef_usuarios',
    'ef_cuentas',
    'ef_invitados',
    'ef_eventos',
    'ef_audiencia_persona_eventos',
    'ef_programa_inscripciones',
    'ef_rsvp_grupos',
    'ef_rsvp_grupo_integrantes',
    'ef_evento_checkins',
    'ef_evento_acceso_links',
    'ef_staff'
]

sync_blocks = []

for table_name, columns_block in tables:
    if table_name not in tables_to_sync:
        continue
    
    block_lines = [f"    -- {table_name}"]
    block_lines.append(f"    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = '{table_name}') THEN")
    
    # Extract columns
    # Split by comma but ignore commas inside parentheses (like decimal(9,6) or jsonb NULL)
    # Simple heuristic: split by newline and find lines that look like columns
    lines = columns_block.split('\n')
    for line in lines:
        line = line.strip()
        if not line or line.startswith('CONSTRAINT') or line.startswith('PRIMARY KEY') or line.startswith('FOREIGN KEY') or line.startswith('UNIQUE'):
            continue
        
        # Remove trailing comma
        if line.endswith(','):
            line = line[:-1]
        
        # Extract name and type
        parts = line.split(maxsplit=1)
        if len(parts) < 2:
            continue
        
        col_name = parts[0].strip('"')
        col_def = parts[1]
        
        # Ignore ID column (primary key usually) - actually better to include all IF NOT EXISTS
        # But we'll skip the GENERATED BY DEFAULT AS IDENTITY columns as they are harder to add to existing tables
        if 'GENERATED BY DEFAULT AS IDENTITY' in col_def:
            continue

        block_lines.append(f"        ALTER TABLE public.{table_name} ADD COLUMN IF NOT EXISTS {col_name} {col_def};")
    
    block_lines.append("    END IF;")
    sync_blocks.append('\n'.join(block_lines))

full_do_block = "DO $$ \nBEGIN\n    -- Sincronización de columnas críticas para tablas que ya existen\n\n" + "\n\n".join(sync_blocks) + "\n\nEND $$;"

print(full_do_block)
