-- =======================================================
-- Script de creación: Módulo Staff de Cuenta
-- Eventia - Gestión de Personal por Unidades
-- =======================================================

-- Tabla principal: ef_staff
-- Un registro = un empleado con código de acceso único.
-- El Administrador carga los datos personales al momento de crear el acceso.
CREATE TABLE IF NOT EXISTS public.ef_staff (
    id_staff             bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta            bigint       NOT NULL REFERENCES public.ef_cuentas(id_cuenta),
    id_rol               smallint     NOT NULL REFERENCES public.ef_roles(id_rol),

    -- Código alfanumérico único: 10 caracteres, sin guiones, sin caracteres ambiguos
    -- Ejemplo: AX4JD92KBT
    codigo               varchar(12)  NOT NULL UNIQUE,

    -- Datos personales registrados por el administrador
    nombre               varchar(100),
    apellido             varchar(100),
    email                varchar(200),
    telefono             varchar(50),

    -- Vencimiento: el owner define cuándo expira. NULL = solo se revoca manualmente.
    fecha_expiracion     timestamptz,

    -- El owner puede desactivar el acceso en cualquier momento
    activo               boolean      NOT NULL DEFAULT true,

    -- Auditoría de uso
    fecha_uso            timestamptz,
    usos                 int          NOT NULL DEFAULT 0,

    fecha_alta           timestamptz  NOT NULL DEFAULT now(),
    fecha_modif          timestamptz
);

-- Índice para búsqueda rápida por código
CREATE INDEX IF NOT EXISTS idx_ef_staff_codigo ON public.ef_staff(codigo);
CREATE INDEX IF NOT EXISTS idx_ef_staff_id_cuenta ON public.ef_staff(id_cuenta);

-- =======================================================
-- Tabla de unidades asignadas al staff
CREATE TABLE IF NOT EXISTS public.ef_staff_unidades (
    id_staff  bigint NOT NULL REFERENCES public.ef_staff(id_staff) ON DELETE CASCADE,
    id_unidad bigint NOT NULL REFERENCES public.ef_cuenta_unidades(id_unidad),
    PRIMARY KEY (id_staff, id_unidad)
);

-- =======================================================
-- Roles de Staff (insertar si no existen)
-- =======================================================
INSERT INTO public.ef_roles (codigo, descripcion, activo) VALUES
    ('STAFF_DJ',        'DJ - Acceso a módulo de música',          true),
    ('STAFF_RECEPTOR',  'Recepción - Acceso a scanner de ingreso',  true),
    ('STAFF_BARTENDER', 'Bartender - Acceso a beneficios',          true),
    ('STAFF_MESERO',    'Mesero - Acceso a módulo de mesas',         true)
ON CONFLICT (codigo) DO NOTHING;
