-- ============================================================
-- Eventia – Script Idempotente Maestro de Sincronización Local
-- Generado: 2026-04-21
-- Este script crea todas las tablas del sistema utilizando 'IF NOT EXISTS'
-- y agrega columnas faltantes a tablas existentes.
-- No incluye datos (solo estructura).
-- ============================================================

-- ------------------------------------------------------------
-- 0. CONFIGURACIÓN INICIAL
-- ------------------------------------------------------------
-- (Asegurarse de estar en el schema public)
SET search_path TO public;

-- ------------------------------------------------------------
-- 1. PARAMÉTRICAS BÁSICAS
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ef_idiomas (
    id_idioma   smallint     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      varchar(5)   NOT NULL,
    nombre      varchar(80)  NOT NULL,
    activo      boolean      NOT NULL DEFAULT true,
    fecha_alta  timestamptz  NOT NULL DEFAULT now(),
    fecha_modif timestamptz
);
ALTER TABLE ef_idiomas ADD COLUMN IF NOT EXISTS codigo      varchar(5)   NOT NULL DEFAULT '';
ALTER TABLE ef_idiomas ADD COLUMN IF NOT EXISTS nombre      varchar(80)  NOT NULL DEFAULT '';
ALTER TABLE ef_idiomas ADD COLUMN IF NOT EXISTS activo      boolean      NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS ef_paises (
    id_pais     smallint     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_iso2 varchar(2)   NOT NULL,
    codigo_iso3 varchar(3),
    activo      boolean      NOT NULL DEFAULT true,
    orden       smallint     NOT NULL DEFAULT 0,
    fecha_alta  timestamptz  NOT NULL DEFAULT now(),
    fecha_modif timestamptz
);
ALTER TABLE ef_paises ADD COLUMN IF NOT EXISTS codigo_iso2 varchar(2)   NOT NULL DEFAULT '';
ALTER TABLE ef_paises ADD COLUMN IF NOT EXISTS codigo_iso3 varchar(3);
ALTER TABLE ef_paises ADD COLUMN IF NOT EXISTS activo      boolean      NOT NULL DEFAULT true;
ALTER TABLE ef_paises ADD COLUMN IF NOT EXISTS orden       smallint     NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS ef_tipos_identificacion_fiscal (
    id_tipo_identificacion_fiscal smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      varchar(30)  NOT NULL,
    id_pais     smallint     NOT NULL REFERENCES ef_paises(id_pais),
    activo      boolean      NOT NULL DEFAULT true,
    orden       smallint     NOT NULL DEFAULT 0,
    fecha_alta  timestamptz  NOT NULL DEFAULT now(),
    fecha_modif timestamptz
);

CREATE TABLE IF NOT EXISTS ef_roles (
    id_rol  integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  varchar(80)  NOT NULL,
    codigo  varchar(30)  NOT NULL,
    activo  boolean      NOT NULL DEFAULT true
);
ALTER TABLE ef_roles ADD COLUMN IF NOT EXISTS activo boolean NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS ef_tipos_evento (
    id_tipo_evento integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo         varchar(20)  NOT NULL,
    nombre         varchar(80)  NOT NULL,
    activo         boolean      NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS ef_dress_code (
    id_dress_code smallint    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        varchar(80) NOT NULL,
    activo        boolean     NOT NULL DEFAULT true
);

-- ------------------------------------------------------------
-- 2. CUENTAS Y USUARIOS
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ef_cuentas (
    id_cuenta   bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      varchar(150) NOT NULL,
    activo      boolean      NOT NULL DEFAULT true,
    fecha_alta  timestamptz  NOT NULL DEFAULT now(),
    fecha_modif timestamptz
);

CREATE TABLE IF NOT EXISTS ef_usuarios (
    id_usuario       bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            varchar(320) NOT NULL UNIQUE,
    password_hash    varchar(255),
    nombre           varchar(80)  NOT NULL,
    apellido         varchar(80)  NOT NULL,
    email_verificado boolean      NOT NULL DEFAULT false,
    activo           boolean      NOT NULL DEFAULT true,
    auth_provider    varchar(20)  NOT NULL DEFAULT 'local',
    google_sub       varchar(50),
    avatar_url       varchar(500),
    telefono         varchar(50),
    id_pais          smallint     REFERENCES ef_paises(id_pais),
    fecha_alta       timestamptz  NOT NULL DEFAULT now(),
    fecha_modif      timestamptz
);
ALTER TABLE ef_usuarios ADD COLUMN IF NOT EXISTS telefono varchar(50);
ALTER TABLE ef_usuarios ADD COLUMN IF NOT EXISTS id_pais  smallint;

CREATE TABLE IF NOT EXISTS ef_usuarios_roles (
    id_usuario_rol bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario     bigint  NOT NULL REFERENCES ef_usuarios(id_usuario),
    id_rol         integer NOT NULL REFERENCES ef_roles(id_rol),
    CONSTRAINT ux_ef_usuarios_roles UNIQUE (id_usuario, id_rol)
);

CREATE TABLE IF NOT EXISTS ef_cuenta_usuarios (
    id_cuenta_usuario bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta         bigint      NOT NULL REFERENCES ef_cuentas(id_cuenta),
    id_usuario        bigint      NOT NULL REFERENCES ef_usuarios(id_usuario),
    activo            boolean     NOT NULL DEFAULT true,
    fecha_alta        timestamptz NOT NULL DEFAULT now(),
    fecha_modif       timestamptz,
    CONSTRAINT ux_cu UNIQUE (id_cuenta, id_usuario)
);

-- ------------------------------------------------------------
-- 3. UNIDADES OPERATIVAS
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ef_cuenta_unidades (
    id_unidad    bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta    bigint       NOT NULL REFERENCES ef_cuentas(id_cuenta),
    codigo       varchar(30)  NOT NULL,
    nombre       varchar(150) NOT NULL,
    descripcion  varchar(500),
    activo       boolean      NOT NULL DEFAULT true,
    fecha_alta   timestamptz  NOT NULL DEFAULT now(),
    fecha_modif  timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_ef_cuenta_unidades_cuenta_codigo ON ef_cuenta_unidades(id_cuenta, codigo);

CREATE TABLE IF NOT EXISTS ef_clientes (
    id_cliente     bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta      bigint       NOT NULL REFERENCES ef_cuentas(id_cuenta),
    nombre_cliente varchar(150) NOT NULL,
    email          varchar(200),
    telefono       varchar(50),
    activo         boolean      NOT NULL DEFAULT true,
    fecha_alta     timestamptz  NOT NULL DEFAULT now(),
    fecha_modif    timestamptz
);

CREATE TABLE IF NOT EXISTS ef_cliente_unidades (
    id_cliente_unidad bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente        bigint NOT NULL REFERENCES ef_clientes(id_cliente),
    id_unidad         bigint NOT NULL REFERENCES ef_cuenta_unidades(id_unidad),
    es_principal      boolean NOT NULL DEFAULT false,
    activo            boolean NOT NULL DEFAULT true,
    fecha_alta        timestamptz NOT NULL DEFAULT now(),
    fecha_modif       timestamptz
);

-- ------------------------------------------------------------
-- 4. STAFF Y PERSONAL
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ef_staff (
    id_staff             bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta            bigint       NOT NULL REFERENCES ef_cuentas(id_cuenta),
    id_rol               smallint     NOT NULL REFERENCES ef_roles(id_rol),
    codigo               varchar(12)  NOT NULL UNIQUE,
    nombre               varchar(100),
    apellido             varchar(100),
    email                varchar(200),
    telefono             varchar(50),
    fecha_expiracion     timestamptz,
    activo               boolean      NOT NULL DEFAULT true,
    fecha_uso            timestamptz,
    usos                 int          NOT NULL DEFAULT 0,
    fecha_alta           timestamptz  NOT NULL DEFAULT now(),
    fecha_modif          timestamptz
);

CREATE TABLE IF NOT EXISTS ef_staff_unidades (
    id_staff  bigint NOT NULL REFERENCES ef_staff(id_staff) ON DELETE CASCADE,
    id_unidad bigint NOT NULL REFERENCES ef_cuenta_unidades(id_unidad),
    PRIMARY KEY (id_staff, id_unidad)
);

-- ------------------------------------------------------------
-- 5. EVENTOS CORE
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ef_eventos (
    id_evento                    bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_evento               integer      NOT NULL REFERENCES ef_tipos_evento(id_tipo_evento),
    id_idioma                    smallint     NOT NULL REFERENCES ef_idiomas(id_idioma),
    id_cliente                   bigint       REFERENCES ef_clientes(id_cliente),
    id_dress_code                smallint     REFERENCES ef_dress_code(id_dress_code),
    anfitriones_texto            varchar(500) NOT NULL,
    estado                       char(1)      NOT NULL DEFAULT 'B',
    fecha_alta                   timestamptz  NOT NULL DEFAULT now(),
    fecha_modif                  timestamptz
);

CREATE TABLE IF NOT EXISTS ef_tramo_tipos (
    id_tramo_tipo smallint    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        varchar(80) NOT NULL,
    codigo        varchar(20) NOT NULL,
    activo        boolean     NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS ef_evento_tramos (
    id_tramo          bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento         bigint         NOT NULL REFERENCES ef_eventos(id_evento) ON DELETE CASCADE,
    id_tramo_tipo     smallint       REFERENCES ef_tramo_tipos(id_tramo_tipo),
    nombre            varchar(80)    NOT NULL,
    fecha_hora_inicio timestamptz    NOT NULL,
    orden             smallint       NOT NULL,
    activo            boolean        NOT NULL DEFAULT true,
    fecha_alta        timestamptz    NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ef_evento_accesos (
    id_acceso    bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento    bigint        NOT NULL REFERENCES ef_eventos(id_evento),
    nombre       varchar(120)  NOT NULL,
    activo       boolean       NOT NULL DEFAULT true,
    fecha_alta   timestamptz   NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------
-- 6. MESAS Y UBICACIÓN
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ef_evento_mesas (
    id_mesa     bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramo    bigint       NOT NULL REFERENCES ef_evento_tramos(id_tramo),
    nombre      varchar(50)  NOT NULL,
    capacidad   int,
    notas       varchar(250),
    activo      boolean      NOT NULL DEFAULT true,
    fecha_alta  timestamptz  NOT NULL DEFAULT now(),
    fecha_modif timestamptz
);

CREATE TABLE IF NOT EXISTS ef_invitados (
    id_invitado          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento            bigint       NOT NULL REFERENCES ef_eventos(id_evento),
    nombre               varchar(80)  NOT NULL,
    apellido             varchar(80)  NOT NULL,
    rsvp_estado          char(1)      NOT NULL DEFAULT 'P',
    activo               boolean      NOT NULL DEFAULT true,
    fecha_alta           timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ef_evento_mesa_invitados (
    id_mesa     bigint NOT NULL REFERENCES ef_evento_mesas(id_mesa) ON DELETE CASCADE,
    id_invitado bigint NOT NULL REFERENCES ef_invitados(id_invitado) ON DELETE CASCADE,
    fecha_alta  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id_mesa, id_invitado)
);

-- ------------------------------------------------------------
-- 7. HOSPEDAJE
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ef_hospedaje_tags (
    id_hospedaje_tag bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo           varchar(40) NOT NULL UNIQUE,
    activo           boolean     NOT NULL DEFAULT true,
    orden            smallint    NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ef_evento_hospedajes (
    id_hospedaje     bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento        bigint       NOT NULL REFERENCES ef_eventos(id_evento),
    nombre           varchar(150) NOT NULL,
    tipo             varchar(20),
    zona             varchar(120),
    direccion        varchar(200),
    url_externa      varchar(400),
    telefono         varchar(40),
    whatsapp         varchar(40),
    latitud          numeric(9,6),
    longitud         numeric(9,6),
    id_tramo_referencia bigint REFERENCES ef_evento_tramos(id_tramo),
    precio_desde     numeric(12,2),
    precio_hasta     numeric(12,2),
    moneda           varchar(3),
    etiquetas        text[],
    nota_publica     varchar(200),
    recomendado      boolean NOT NULL DEFAULT false,
    orden            smallint NOT NULL DEFAULT 1,
    activo           boolean NOT NULL DEFAULT true,
    fecha_alta       timestamptz NOT NULL DEFAULT now(),
    fecha_modif      timestamptz
);

CREATE TABLE IF NOT EXISTS ef_evento_hospedaje_bloques (
    id_bloque          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hospedaje       bigint       NOT NULL REFERENCES ef_evento_hospedajes(id_hospedaje) ON DELETE CASCADE,
    nombre_reserva     varchar(120),
    codigo_promocional varchar(60),
    condiciones        varchar(240),
    url_bloque         varchar(400),
    activo             boolean NOT NULL DEFAULT true,
    fecha_alta         timestamptz NOT NULL DEFAULT now(),
    fecha_modif        timestamptz
);

CREATE TABLE IF NOT EXISTS ef_cuenta_hospedaje_plantillas (
    id_hospedaje_plantilla bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta              bigint NOT NULL REFERENCES ef_cuentas(id_cuenta),
    id_unidad              bigint REFERENCES ef_cuenta_unidades(id_unidad),
    codigo                 varchar(30),
    nombre                 varchar(120) NOT NULL,
    descripcion            varchar(300),
    ciudad                 varchar(100),
    zona                   varchar(120),
    id_pais                smallint REFERENCES ef_paises(id_pais),
    activo                 boolean NOT NULL DEFAULT true,
    fecha_alta             timestamptz NOT NULL DEFAULT now(),
    fecha_modif            timestamptz
);

CREATE TABLE IF NOT EXISTS ef_cuenta_hospedaje_plantilla_items (
    id_hospedaje_plantilla_item bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hospedaje_plantilla      bigint NOT NULL REFERENCES ef_cuenta_hospedaje_plantillas(id_hospedaje_plantilla) ON DELETE CASCADE,
    nombre                      varchar(150) NOT NULL,
    tipo                        varchar(20),
    zona                        varchar(120),
    direccion                   varchar(200),
    url_externa                 varchar(400),
    telefono                    varchar(40),
    whatsapp                    varchar(40),
    latitud                     numeric(9,6),
    longitud                    numeric(9,6),
    etiquetas                   text[] DEFAULT '{}',
    nota_publica                varchar(200),
    recomendado                 boolean NOT NULL DEFAULT false,
    orden                       smallint NOT NULL DEFAULT 1,
    activo                      boolean NOT NULL DEFAULT true,
    fecha_alta                  timestamptz NOT NULL DEFAULT now(),
    fecha_modif                 timestamptz
);

CREATE TABLE IF NOT EXISTS ef_cuenta_hospedaje_plantilla_item_bloques (
    id_bloque                   bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hospedaje_plantilla_item bigint       NOT NULL REFERENCES ef_cuenta_hospedaje_plantilla_items(id_hospedaje_plantilla_item) ON DELETE CASCADE,
    nombre_reserva              varchar(120),
    codigo_promocional          varchar(60),
    condiciones                 varchar(240),
    url_bloque                  varchar(400),
    activo                      boolean NOT NULL DEFAULT true,
    fecha_alta                  timestamptz NOT NULL DEFAULT now(),
    fecha_modif                 timestamptz
);

-- ------------------------------------------------------------
-- 8. AUDIENCIA Y CHECKINS
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ef_audiencias_personas (
    id_audiencia_persona bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cuenta            bigint NOT NULL REFERENCES ef_cuentas(id_cuenta),
    nombre               varchar(120) NOT NULL,
    apellido             varchar(120) NOT NULL,
    email                varchar(200),
    celular              varchar(50),
    instagram            varchar(100),
    zona                 varchar(120),
    ciudad               varchar(120),
    acepta_comunicaciones boolean NOT NULL DEFAULT false,
    acepta_promociones    boolean NOT NULL DEFAULT false,
    activo               boolean NOT NULL DEFAULT true,
    fecha_alta           timestamptz NOT NULL DEFAULT now(),
    fecha_modif          timestamptz
);

CREATE TABLE IF NOT EXISTS ef_audiencia_persona_eventos (
    id_audiencia_persona_evento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_audiencia_persona        bigint NOT NULL REFERENCES ef_audiencias_personas(id_audiencia_persona),
    id_evento                   bigint NOT NULL REFERENCES ef_eventos(id_evento),
    id_unidad                   bigint REFERENCES ef_cuenta_unidades(id_unidad),
    id_invitado                 bigint REFERENCES ef_invitados(id_invitado),
    id_acceso                   bigint REFERENCES ef_evento_accesos(id_acceso),
    origen_registro             varchar(80),
    registrado                  boolean NOT NULL DEFAULT true,
    asistio                     boolean NOT NULL DEFAULT false,
    beneficio_otorgado          boolean NOT NULL DEFAULT false,
    beneficio_canjeado          boolean NOT NULL DEFAULT false,
    fecha_registro              timestamptz NOT NULL DEFAULT now(),
    fecha_asistencia            timestamptz,
    fecha_modif                 timestamptz
);

CREATE TABLE IF NOT EXISTS ef_audiencia_persona_tags (
    id_audiencia_persona_tag bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_audiencia_persona     bigint NOT NULL REFERENCES ef_audiencias_personas(id_audiencia_persona),
    tag_tipo                 varchar(60) NOT NULL,
    tag_valor                varchar(120) NOT NULL,
    activo                   boolean NOT NULL DEFAULT true,
    fecha_alta               timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ef_evento_checkins (
    id_checkin          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento           bigint NOT NULL REFERENCES ef_eventos(id_evento),
    id_invitado         bigint NOT NULL REFERENCES ef_invitados(id_invitado),
    id_acceso           bigint REFERENCES ef_evento_accesos(id_acceso),
    id_acceso_link      bigint,
    id_usuario_operador bigint REFERENCES ef_usuarios(id_usuario),
    tipo                varchar(30) NOT NULL, -- QR / LISTA / MANUAL
    fecha               timestamptz NOT NULL DEFAULT now(),
    observaciones       varchar(500)
);

CREATE TABLE IF NOT EXISTS ef_invitado_perfiles (
    id_invitado         bigint PRIMARY KEY REFERENCES ef_invitados(id_invitado),
    id_perfil_asistencia int,
    instagram           varchar(100),
    zona                varchar(120),
    ciudad              varchar(100),
    origen_registro     varchar(30),
    pagina_origen       varchar(200),
    fecha_alta          timestamptz NOT NULL DEFAULT now(),
    fecha_modif         timestamptz
);

-- ------------------------------------------------------------
-- 9. BENEFICIOS Y PARAMÉTRICAS ADICIONALES
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ef_param_perfiles_asistencia (
    id_perfil_asistencia int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo               varchar(80) NOT NULL,
    activo               boolean NOT NULL DEFAULT true,
    orden                int NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ef_param_tipos_beneficio_registro (
    id_tipo_beneficio_registro int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                     varchar(40) NOT NULL UNIQUE,
    activo                     boolean NOT NULL DEFAULT true,
    orden                      int NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ef_evento_beneficios_registro (
    id_beneficio_registro    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento               bigint NOT NULL REFERENCES ef_eventos(id_evento),
    id_invitado             bigint NOT NULL REFERENCES ef_invitados(id_invitado),
    id_tipo_beneficio_registro int NOT NULL REFERENCES ef_param_tipos_beneficio_registro(id_tipo_beneficio_registro),
    titulo_snapshot         varchar(120) NOT NULL,
    descripcion_snapshot    varchar(250),
    estado                  char(1) NOT NULL DEFAULT 'G', -- G: Generado, C: Canjeado, V: Vencido
    codigo_canje            varchar(64),
    fecha_otorgado          timestamptz NOT NULL DEFAULT now(),
    fecha_canje             timestamptz,
    fecha_vencimiento       timestamptz,
    id_usuario_valida       bigint REFERENCES ef_usuarios(id_usuario),
    observaciones           varchar(250)
);

CREATE TABLE IF NOT EXISTS ef_param_intereses_evento_publico (
    id_interes_evento_publico int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                    varchar(80) NOT NULL,
    activo                    boolean NOT NULL DEFAULT true,
    orden                     int NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ef_param_preferencias_musicales (
    id_preferencia_musical int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                 varchar(80) NOT NULL,
    activo                 boolean NOT NULL DEFAULT true,
    orden                  int NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ef_invitado_intereses_evento (
    id_invitado                bigint NOT NULL REFERENCES ef_invitados(id_invitado),
    id_interes_evento_publico  int NOT NULL REFERENCES ef_param_intereses_evento_publico(id_interes_evento_publico),
    fecha_alta                 timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id_invitado, id_interes_evento_publico)
);

CREATE TABLE IF NOT EXISTS ef_invitado_preferencias_musicales (
    id_invitado            bigint NOT NULL REFERENCES ef_invitados(id_invitado),
    id_preferencia_musical int NOT NULL REFERENCES ef_param_preferencias_musicales(id_preferencia_musical),
    fecha_alta             timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (id_invitado, id_preferencia_musical)
);

-- ------------------------------------------------------------
-- FIN DEL SCRIPT MAESTRO
-- ------------------------------------------------------------
