///////////////////////////////////////////////////////////
//  EstadoTramite.cs
//  Implementation of the Class EstadoTramite
//  Generated by Enterprise Architect
//  Created on:      03-jun.-2024 10:25:51
//  Original author: gcassulo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace API.DataSchema
{
	public class ANT_EstadoTramites
	{

		public int IdEstadoTramite { get; set; }
		public string Estado { get; set; }
        public virtual ICollection<ANT_Expedientes>? Expedientes { get; set; } = new List<ANT_Expedientes>(); // Collection navigation containing dependents

    }
}