///////////////////////////////////////////////////////////
//  Prestadores.cs
//  Implementation of the Class Apoderado
//  Generated by Enterprise Architect
//  Created on:      03-jun.-2024 10:25:39
//  Original author: gcassulo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace API.DataSchema { 
public class Prestadores {

		public int IdPrestador { get; set; }
		public int IdApoderado { get; set; }
		public int Cuit { get; set; }
		public string Direccion { get; set; }
		public string RazonSocial { get; set; }

		public virtual ICollection<ANT_Antenas>? Antenas { get; set; } = new List<ANT_Antenas>();
		public virtual ICollection<Apoderados>? Apoderados { get; set;} = new List<Apoderados>();

    } 
}