///////////////////////////////////////////////////////////
//  Inspecciones.cs
//  Implementation of the Class Inspecciones
//  Generated by Enterprise Architect
//  Created on:      03-jun.-2024 10:25:53
//  Original author: gcassulo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace API.DataSchema { 
public class ANT_Inspecciones {

    public int IdInspeccion { get; set; }
    public int IdAntena { get; set; }
	public int IdUsuario { get; set; }
	public string AlambradoPerimetral { get; set; }
	public string AnilloTierra { get; set; }
	public string BalizaFlash { get; set; }
	public string BarraEquipos { get; set; }
	public string BarraEstructura { get; set; }
	public string BaseConcreto { get; set; }
	public string BaseConcretoPrin { get; set; }
	public string Bulones { get; set; }
	public string CableAlimentacion { get; set; }
	public string  CableDescarga { get; set; }
	public string  CamaraInspeccion { get; set; }
	public string CamaraPararrayos { get; set; }
	public string CamarasInspec { get; set; }
	public string CamarasPase { get; set; }
	public string CanalPilar { get; set; }
	public string ConexionBarra { get; set; }
	public string ConexionChasis { get; set; }
	public string ConexionEstAnillo { get; set; }
	public string ConexionTierra { get; set; }
	public string Desmalezado { get; set; }
	public string DesplaFisuras { get; set; }
	public string ErosionTerreno { get; set; }
	public string EscaleraGuarda { get; set; }
	public string EstadoFotocelula { get; set; }
	public string EstadoGral { get; set; }
	public string EstanqueCañerias { get; set; }
	public string EstrTransicion { get; set; }
	public DateTime Fecha { get; set; }
	public string GrasaAntiox { get; set; }
	public string Grietas { get; set; }
	public string IluminacionBanquina { get; set; }
	public string LucesBaliza { get; set; }
	public string Mastil { get; set; }
	public string ObjetosExtraños { get; set; }
	public string Observaciones { get; set; }
	public string ObstruccionesCaños { get; set; }
	public string PedestalConcreto { get; set; }
	public string PernosFijaEstructura { get; set; }
	public string PernosFijaGabinetes { get; set; }
	public string PernosFijaPedestales { get; set; }
	public string PernosFijaPerfil { get; set; }
	public string PernosViga { get; set; }
	public string PilarMedicion { get; set; }
	public string PinturaBaliza { get; set; }
	public string PinturaBanquina { get; set; }
	public string PlataformasInspeccion { get; set; }
	public string PortoAcceso { get; set; }
	public string ProteccionTermo { get; set; }
	public string PuertaBanquina { get; set; }
	public string PuntaCaptora { get; set; }
	public string PuntosHumedad { get; set; }
	public string Razon { get; set; }
	public string RoturaPedestales { get; set; }
	public string SalvaCaidas { get; set; }
	public string SimboloRiesgoElec { get; set; }
	public string SoporteBalizas { get; set; }
	public string SoportesBandejas { get; set; }
	public string SoportesCañerias { get; set; }
	public string SoportesFijaciones { get; set; }
	public string TableroBaliza { get; set; }
	public string TableroEmergencia { get; set; }
	public string TableroGralCA { get; set; }
	public string TableroPrincipal { get; set; }
	public string UCLA { get; set; }
	public string UnionesTramos { get; set; }
	public string Verticalidad { get; set; }
	public string VigaEquipos { get; set; }
	public string Visibilidad { get; set; }
	public virtual ANT_Antenas? Antena { get; set; }

    }

}//end Inspecciones