///////////////////////////////////////////////////////////
//  Expediente.cs
//  Implementation of the Class Expediente
//  Generated by Enterprise Architect
//  Created on:      03-jun.-2024 10:25:52
//  Original author: gcassulo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace API.DataSchema
{
	public class ANT_Expedientes
	{

		public int IdExpediente { get; set; }
        public int? IdAntena { get; set; }
		public string AcometidaEnergia { get; set; }
		public string ActaAsamblea { get; set; }
		public string AEnacom { get; set; }
		public string ANAC { get; set; }
		public string CertificadoDominio { get; set; }
		public string CompromisoDesmonte { get; set; }
		public string ConstanciaPago { get; set; }
		public string ContratoLocacion { get; set; }
		public string ContratoRepresentante { get; set; }
		public string ContratoResponsableSH { get; set; }
		public string CopiaConvenioCNC { get; set; }
		public string CronogramaObra { get; set; }
		public string CuadroPotencia { get; set; }
		public string CuadroVerifConduc { get; set; }
		public string FactAmbienteBA { get; set; }
		public DateTime FechaEmision { get; set; }
		public DateTime FechaTasaA { get; set; }
		public string ImpactoAmbiental { get; set; }
		public string LayoutElectrica { get; set; }
		public string LibreDeuda { get; set; }
		public string MedicionRadiacion { get; set; }
		public string MemoriaCalculo { get; set; }
		public string NombreExp { get; set; }
		public string NroExpediente { get; set; }
		public string Observaciones { get; set; }
		public string OrdenamientoTerritorial { get; set; }
		public string PermisoAmbiental { get; set; }
		public string PlanoCivil { get; set; }
		public string PlanoConstruccion { get; set; }
		public string Planos { get; set; }
		public string PoderTramite { get; set; }
		public string PolizaSeguroCT { get; set; }
		public string RegistroDGOP { get; set; }
		public string ReglamentoCopropiedad { get; set; }
		public string SeguridadHigiene { get; set; }
		public string SeguroRespCivil { get; set; }
		public string SistBaliza { get; set; }
		public string SistProtAtmos { get; set; }
		public string SistPuestaTierra { get; set; }
		public string TasaAnual { get; set; }
		public string TasaSigem { get; set; }
		public string UnifiliarGral { get; set; }
		public virtual ANT_Antenas? Antenas { get; set; }
		public virtual ANT_EstadoTramite? EstadoTramite { get;}

	}
}