///////////////////////////////////////////////////////////
//  Apoderados.cs
//  Implementation of the Class TipoAntenas
//  Generated by Enterprise Architect
//  Created on:      03-jun.-2024 10:25:39
//  Original author: gcassulo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace API.DataSchema
{
	public class ANT_Apoderados
	{

		public int IdApoderado { get; set; }
		public string Nombre { get; set; }
		public string Apelllido { get; set; }
		public int NroDoc { get; set; }
		public virtual ICollection<ANT_Prestadores>? Prestador { get; set; } = new List<ANT_Prestadores>();
	}
}