///////////////////////////////////////////////////////////
//  Antenas.cs
//  Implementation of the Class Apoderado
//  Generated by Enterprise Architect
//  Created on:      03-jun.-2024 10:25:39
//  Original author: gcassulo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace API.DataSchema
{
	public class ANT_Antenas
	{

		public int IdAntena { get; set; }
		public int? IdTipoAntena { get; set; }
		public int? IdPrestador { get; set; }
		public int? IdExpediente { get; set; }
		public float AlturaSoporte { get; set; }
		public float AlturaTotal { get; set; }
		public string CellId { get; set; }
		public int CodigoSitio { get; set; }
		public string Declarada { get; set; }
		public string Direccion { get; set; }
		public string Emplazamiento { get; set; }
		public string Observaciones { get; set; }
		public string SalaEquipos { get; set; }
		public string TipoMimetizado { get; set; }
		public virtual ANT_TipoAntenas? TipoAntenas { get; set; }
		public virtual ANT_Expedientes? Expediente { get; set; }
		public virtual ANT_Prestadores? Prestador { get; set; }
        
        public virtual ICollection<ANT_Inspecciones>? Inspecciones { get; set; } = new List<ANT_Inspecciones>();



	}
}
