///////////////////////////////////////////////////////////
//  ApoderadoXPrestador.cs
//  Implementation of the Class ApoderadoXPrestador
//  Generated by Enterprise Architect
//  Created on:      03-jun.-2024 10:25:50
//  Original author: gcassulo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace API.DataSchema
{
	public class ApoderadoXPrestador
	{

		public int IdApoderadoXprestador { get; set; }
		public int IdApoderado { get; set; }
		public int IdPrestador { get; set; }
		public int IdUsuario { get; set; }
		public DateTime Fecha { get; set; }

		public virtual ICollection<Apoderados>? Apoderados { get; set; } = new List<Apoderados>();
		public virtual ICollection<Prestadores>? Prestadores { get; set; } = new List<Prestadores>();
		
		public virtual ICollection<Usuario>? Usuarios { get; set; } = new List<Usuario>();

	}
}