///////////////////////////////////////////////////////////
//  Inspecciones.cs
//  Implementation of the Class Inspecciones
//  Generated by Enterprise Architect
//  Created on:      03-jun.-2024 10:25:53
//  Original author: gcassulo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace API.DataSchema { 
public class Inspecciones {

	public string AlambradoPerimetral { get; set; }
	public string AnilloTierra { get; set; }
	public string BalizaFlash { get; set; }
	public string BarraEquipos { get; set; }
	public string BarraEstructura { get; set; }
	public string BaseConcreto { get; set; }
	public string BaseConcretoPrin { get; set; }
	public string Bulones { get; set; }
	public string CableAlimentacion { get; set; }
	public string  CableDescarga { get; set; }
	public string  CamaraInspeccion { get; set; }
	public string CamaraPararrayos { get; set; }
	public string CamarasInspec { get; set; }
	public string CamarasPase { get; set; }
	public string CanalPilar { get; set; }
	public string ConexionBarra { get; set; }
	public string ConexionChasis { get; set; }
	private char ConexionEstAnillo;
	private char ConexionTierra;
	private char Desmalezado;
	private char DesplaFisuras;
	private char ErosionTerreno;
	private char EscaleraGuarda;
	private char EstadoFotocelula;
	private char EstadoGral;
	private char EstanqueCañerias;
	private char EstrTransicion;
	private DateTime Fecha;
	private char GrasaAntiox;
	private char Grietas;
	private int IdAntena;
	private int IdInspeccion;
	private int IdLeyenda;
	private int IdUsuario;
	private char IluminacionBanquina;
	private char LucesBaliza;
	private char Mastil;
	private char ObjetosExtraños;
	private string Observaciones;
	private char ObstruccionesCaños;
	private char PedestalConcreto;
	private char PernosFijaEstructura;
	private char PernosFijaGabinetes;
	private char PernosFijaPedestales;
	private char PernosFijaPerfil;
	private char PernosViga;
	private char PilarMedicion;
	private char PinturaBaliza;
	private char PinturaBanquina;
	private char PlataformasInspeccion;
	private char PortoAcceso;
	private char ProteccionTermo;
	private char PuertaBanquina;
	private char PuntaCaptora;
	private char PuntosHumedad;
	private string Razon;
	private char RoturaPedestales;
	private char SalvaCaidas;
	private char SimboloRiesgoElec;
	private char SoporteBalizas;
	private char SoportesBandejas;
	private char SoportesCañerias;
	private char SoportesFijaciones;
	private char TableroBaliza;
	private char TableroEmergencia;
	private char TableroGralCA;
	private char TableroPrincipal;
	private char UCLA;
	private char UnionesTramos;
	private char Verticalidad;
	private char VigaEquipos;
	private char Visibilidad;
	public Usuario m_Usuario;
	public Leyenda m_Leyenda;

    }

}//end Inspecciones