///////////////////////////////////////////////////////////
//  Leyenda.cs
//  Implementation of the Class Leyenda
//  Generated by Enterprise Architect
//  Created on:      03-jun.-2024 10:25:53
//  Original author: gcassulo
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace API.DataSchema
{
	public class Leyenda
	{

		public int IdLeyenda { get; set; }
		public string Nombre { get; set; }

		public Leyenda()
		{

		}

	}
}