START TRANSACTION;

CREATE TABLE "ANT_Apoderados" (
    "IdApoderado" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Apelllido" text NOT NULL,
    "NroDoc" integer NOT NULL,
    CONSTRAINT "PK_ANT_Apoderados" PRIMARY KEY ("IdApoderado")
);

CREATE TABLE "ANT_EstadoTramites" (
    "IdEstado" integer GENERATED BY DEFAULT AS IDENTITY,
    "Estado" text NOT NULL,
    CONSTRAINT "PK_ANT_EstadoTramites" PRIMARY KEY ("IdEstado")
);

CREATE TABLE "ANT_Prestadores" (
    "IdPrestador" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdApoderado" integer NOT NULL,
    "Cuit" integer NOT NULL,
    "Direccion" text NOT NULL,
    "RazonSocial" text NOT NULL,
    CONSTRAINT "PK_ANT_Prestadores" PRIMARY KEY ("IdPrestador")
);

CREATE TABLE "ANT_TipoAntenas" (
    "IdTipoAntena" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_ANT_TipoAntenas" PRIMARY KEY ("IdTipoAntena")
);

CREATE TABLE "ANT_Usuarios" (
    "IdUsuario" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NULL,
    "Email" text NOT NULL,
    "Activo" boolean NULL,
    CONSTRAINT "PK_ANT_Usuarios" PRIMARY KEY ("IdUsuario")
);

CREATE TABLE "ANT_ApoderadosANT_Prestadores" (
    "ApoderadosIdApoderado" integer NOT NULL,
    "PrestadorIdPrestador" integer NOT NULL,
    CONSTRAINT "PK_ANT_ApoderadosANT_Prestadores" PRIMARY KEY ("ApoderadosIdApoderado", "PrestadorIdPrestador"),
    CONSTRAINT "FK_ANT_ApoderadosANT_Prestadores_ANT_Apoderados_ApoderadosIdAp~" FOREIGN KEY ("ApoderadosIdApoderado") REFERENCES "ANT_Apoderados" ("IdApoderado") ON DELETE CASCADE,
    CONSTRAINT "FK_ANT_ApoderadosANT_Prestadores_ANT_Prestadores_PrestadorIdPr~" FOREIGN KEY ("PrestadorIdPrestador") REFERENCES "ANT_Prestadores" ("IdPrestador") ON DELETE CASCADE
);

CREATE TABLE "ANT_Antenas" (
    "IdAntena" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdTipoAntena" integer NOT NULL,
    "IdPrestador" integer NULL,
    "IdExpediente" integer NULL,
    "AlturaSoporte" real NOT NULL,
    "AlturaTotal" real NOT NULL,
    "CellId" text NOT NULL,
    "CodigoSitio" integer NOT NULL,
    "Declarada" text NOT NULL,
    "Direccion" text NOT NULL,
    "Emplazamiento" text NOT NULL,
    "Observaciones" text NOT NULL,
    "SalaEquipos" text NOT NULL,
    "TipoMimetizado" text NOT NULL,
    CONSTRAINT "PK_ANT_Antenas" PRIMARY KEY ("IdAntena"),
    CONSTRAINT "FK_ANT_Antenas_ANT_Prestadores_IdPrestador" FOREIGN KEY ("IdPrestador") REFERENCES "ANT_Prestadores" ("IdPrestador"),
    CONSTRAINT "FK_ANT_Antenas_ANT_TipoAntenas_IdTipoAntena" FOREIGN KEY ("IdTipoAntena") REFERENCES "ANT_TipoAntenas" ("IdTipoAntena") ON DELETE CASCADE
);

CREATE TABLE "ANT_Expedientes" (
    "IdExpediente" integer NOT NULL,
    "IdLeyenda" integer NOT NULL,
    "IdAntena" integer NULL,
    "AcometidaEnergia" text NOT NULL,
    "ActaAsamblea" text NOT NULL,
    "AEnacom" text NOT NULL,
    "ANAC" text NOT NULL,
    "CertificadoDominio" text NOT NULL,
    "CompromisoDesmonte" text NOT NULL,
    "ConstanciaPago" text NOT NULL,
    "ContratoLocacion" text NOT NULL,
    "ContratoRepresentante" text NOT NULL,
    "ContratoResponsableSH" text NOT NULL,
    "CopiaConvenioCNC" text NOT NULL,
    "CronogramaObra" text NOT NULL,
    "CuadroPotencia" text NOT NULL,
    "CuadroVerifConduc" text NOT NULL,
    "FactAmbienteBA" text NOT NULL,
    "FechaEmision" timestamp without time zone NOT NULL,
    "FechaTasaA" timestamp without time zone NOT NULL,
    "ImpactoAmbiental" text NOT NULL,
    "LayoutElectrica" text NOT NULL,
    "LibreDeuda" text NOT NULL,
    "MedicionRadiacion" text NOT NULL,
    "MemoriaCalculo" text NOT NULL,
    "NombreExp" text NOT NULL,
    "NroExpediente" text NOT NULL,
    "Observaciones" text NOT NULL,
    "OrdenamientoTerritorial" text NOT NULL,
    "PermisoAmbiental" text NOT NULL,
    "PlanoCivil" text NOT NULL,
    "PlanoConstruccion" text NOT NULL,
    "Planos" text NOT NULL,
    "PoderTramite" text NOT NULL,
    "PolizaSeguroCT" text NOT NULL,
    "RegistroDGOP" text NOT NULL,
    "ReglamentoCopropiedad" text NOT NULL,
    "SeguridadHigiene" text NOT NULL,
    "SeguroRespCivil" text NOT NULL,
    "SistBaliza" text NOT NULL,
    "SistProtAtmos" text NOT NULL,
    "SistPuestaTierra" text NOT NULL,
    "TasaAnual" text NOT NULL,
    "TasaSigem" text NOT NULL,
    "UnifiliarGral" text NOT NULL,
    CONSTRAINT "PK_ANT_Expedientes" PRIMARY KEY ("IdExpediente"),
    CONSTRAINT "FK_ANT_Expedientes_ANT_Antenas_IdExpediente" FOREIGN KEY ("IdExpediente") REFERENCES "ANT_Antenas" ("IdAntena") ON DELETE CASCADE,
    CONSTRAINT "FK_ANT_Expedientes_ANT_EstadoTramites_IdExpediente" FOREIGN KEY ("IdExpediente") REFERENCES "ANT_EstadoTramites" ("IdEstado") ON DELETE CASCADE
);

CREATE TABLE "ANT_Inspecciones" (
    "IdInspeccion" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdAntena" integer NOT NULL,
    "IdLeyenda" integer NOT NULL,
    "IdUsuario" integer NOT NULL,
    "AlambradoPerimetral" text NOT NULL,
    "AnilloTierra" text NOT NULL,
    "BalizaFlash" text NOT NULL,
    "BarraEquipos" text NOT NULL,
    "BarraEstructura" text NOT NULL,
    "BaseConcreto" text NOT NULL,
    "BaseConcretoPrin" text NOT NULL,
    "Bulones" text NOT NULL,
    "CableAlimentacion" text NOT NULL,
    "CableDescarga" text NOT NULL,
    "CamaraInspeccion" text NOT NULL,
    "CamaraPararrayos" text NOT NULL,
    "CamarasInspec" text NOT NULL,
    "CamarasPase" text NOT NULL,
    "CanalPilar" text NOT NULL,
    "ConexionBarra" text NOT NULL,
    "ConexionChasis" text NOT NULL,
    "ConexionEstAnillo" text NOT NULL,
    "ConexionTierra" text NOT NULL,
    "Desmalezado" text NOT NULL,
    "DesplaFisuras" text NOT NULL,
    "ErosionTerreno" text NOT NULL,
    "EscaleraGuarda" text NOT NULL,
    "EstadoFotocelula" text NOT NULL,
    "EstadoGral" text NOT NULL,
    "EstanqueCañerias" text NOT NULL,
    "EstrTransicion" text NOT NULL,
    "Fecha" timestamp without time zone NOT NULL,
    "GrasaAntiox" text NOT NULL,
    "Grietas" text NOT NULL,
    "IluminacionBanquina" text NOT NULL,
    "LucesBaliza" text NOT NULL,
    "Mastil" text NOT NULL,
    "ObjetosExtraños" text NOT NULL,
    "Observaciones" text NOT NULL,
    "ObstruccionesCaños" text NOT NULL,
    "PedestalConcreto" text NOT NULL,
    "PernosFijaEstructura" text NOT NULL,
    "PernosFijaGabinetes" text NOT NULL,
    "PernosFijaPedestales" text NOT NULL,
    "PernosFijaPerfil" text NOT NULL,
    "PernosViga" text NOT NULL,
    "PilarMedicion" text NOT NULL,
    "PinturaBaliza" text NOT NULL,
    "PinturaBanquina" text NOT NULL,
    "PlataformasInspeccion" text NOT NULL,
    "PortoAcceso" text NOT NULL,
    "ProteccionTermo" text NOT NULL,
    "PuertaBanquina" text NOT NULL,
    "PuntaCaptora" text NOT NULL,
    "PuntosHumedad" text NOT NULL,
    "Razon" text NOT NULL,
    "RoturaPedestales" text NOT NULL,
    "SalvaCaidas" text NOT NULL,
    "SimboloRiesgoElec" text NOT NULL,
    "SoporteBalizas" text NOT NULL,
    "SoportesBandejas" text NOT NULL,
    "SoportesCañerias" text NOT NULL,
    "SoportesFijaciones" text NOT NULL,
    "TableroBaliza" text NOT NULL,
    "TableroEmergencia" text NOT NULL,
    "TableroGralCA" text NOT NULL,
    "TableroPrincipal" text NOT NULL,
    "UCLA" text NOT NULL,
    "UnionesTramos" text NOT NULL,
    "Verticalidad" text NOT NULL,
    "VigaEquipos" text NOT NULL,
    "Visibilidad" text NOT NULL,
    CONSTRAINT "PK_ANT_Inspecciones" PRIMARY KEY ("IdInspeccion"),
    CONSTRAINT "FK_ANT_Inspecciones_ANT_Antenas_IdAntena" FOREIGN KEY ("IdAntena") REFERENCES "ANT_Antenas" ("IdAntena") ON DELETE CASCADE
);

CREATE INDEX "IX_ANT_Antenas_IdPrestador" ON "ANT_Antenas" ("IdPrestador");

CREATE INDEX "IX_ANT_Antenas_IdTipoAntena" ON "ANT_Antenas" ("IdTipoAntena");

CREATE INDEX "IX_ANT_ApoderadosANT_Prestadores_PrestadorIdPrestador" ON "ANT_ApoderadosANT_Prestadores" ("PrestadorIdPrestador");

CREATE INDEX "IX_ANT_Inspecciones_IdAntena" ON "ANT_Inspecciones" ("IdAntena");

COMMIT;

