// <auto-generated />
using API.DataSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240822122421_personas2")]
    partial class personas2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.DataSchema.MEC_CarRevista", b =>
                {
                    b.Property<int>("IdCarRevista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCarRevista"));

                    b.Property<string>("CodMgp")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("CodPcia")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength(false);

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdCarRevista");

                    b.ToTable("MEC_CarRevista");
                });

            modelBuilder.Entity("API.DataSchema.MEC_Conceptos", b =>
                {
                    b.Property<int>("IdConcepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConcepto"));

                    b.Property<string>("CodConcepto")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<string>("CodConceptoMgp")
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("ConAporte")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength(false);

                    b.Property<string>("Patronal")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdConcepto");

                    b.ToTable("MEC_Conceptos");
                });

            modelBuilder.Entity("API.DataSchema.MEC_Establecimientos", b =>
                {
                    b.Property<int>("IdEstablecimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstablecimiento"));

                    b.Property<string>("CantSecciones")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("CantTurnos")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<int>("IdTipoEstablecimiento")
                        .HasColumnType("integer");

                    b.Property<string>("NombreMgp")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("NombrePcia")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("NroDiegep")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<string>("NroEstablecimiento")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength(false);

                    b.Property<string>("Ruralidad")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Subvencion")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength(false);

                    b.Property<string>("UE")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength(false);

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdEstablecimiento");

                    b.HasIndex("IdTipoEstablecimiento");

                    b.ToTable("MEC_Establecimientos");
                });

            modelBuilder.Entity("API.DataSchema.MEC_Personas", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdPersona");

                    b.ToTable("MEC_Personas");
                });

            modelBuilder.Entity("API.DataSchema.MEC_TiposEstablecimientos", b =>
                {
                    b.Property<int>("IdTipoEstablecimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoEstablecimiento"));

                    b.Property<string>("CodTipoEstablecimiento")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength(false);

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdTipoEstablecimiento");

                    b.ToTable("MEC_TiposEstablecimientos");
                });

            modelBuilder.Entity("API.DataSchema.MEC_Establecimientos", b =>
                {
                    b.HasOne("API.DataSchema.MEC_TiposEstablecimientos", "TipoEstablecimientos")
                        .WithMany("Establecimientos")
                        .HasForeignKey("IdTipoEstablecimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEstablecimientos");
                });

            modelBuilder.Entity("API.DataSchema.MEC_TiposEstablecimientos", b =>
                {
                    b.Navigation("Establecimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
