// <auto-generated />
using System;
using API.DataSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240725130658_UpdateANTExpedientesConfiguration")]
    partial class UpdateANTExpedientesConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ANT_ApoderadosANT_Prestadores", b =>
                {
                    b.Property<int>("ApoderadosIdApoderado")
                        .HasColumnType("integer");

                    b.Property<int>("PrestadorIdPrestador")
                        .HasColumnType("integer");

                    b.HasKey("ApoderadosIdApoderado", "PrestadorIdPrestador");

                    b.HasIndex("PrestadorIdPrestador");

                    b.ToTable("ANT_ApoderadosANT_Prestadores");
                });

            modelBuilder.Entity("API.DataSchema.ANT_Antenas", b =>
                {
                    b.Property<int>("IdAntena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAntena"));

                    b.Property<float>("AlturaSoporte")
                        .HasColumnType("real");

                    b.Property<float>("AlturaTotal")
                        .HasColumnType("real");

                    b.Property<string>("CellId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CodigoSitio")
                        .HasColumnType("integer");

                    b.Property<string>("Declarada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Emplazamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IdExpediente")
                        .HasColumnType("integer");

                    b.Property<int?>("IdPrestador")
                        .HasColumnType("integer");

                    b.Property<int?>("IdTipoAntena")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SalaEquipos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoMimetizado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAntena");

                    b.HasIndex("IdPrestador");

                    b.HasIndex("IdTipoAntena");

                    b.ToTable("ANT_Antenas");
                });

            modelBuilder.Entity("API.DataSchema.ANT_Apoderados", b =>
                {
                    b.Property<int>("IdApoderado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdApoderado"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NroDoc")
                        .HasColumnType("integer");

                    b.HasKey("IdApoderado");

                    b.ToTable("ANT_Apoderados");
                });

            modelBuilder.Entity("API.DataSchema.ANT_EstadoTramite", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEstado");

                    b.ToTable("ANT_EstadoTramites");
                });

            modelBuilder.Entity("API.DataSchema.ANT_Expedientes", b =>
                {
                    b.Property<int>("IdExpediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("AEnacom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ANAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ANT_EstadoTramiteIdEstado")
                        .HasColumnType("integer");

                    b.Property<string>("AcometidaEnergia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActaAsamblea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CertificadoDominio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompromisoDesmonte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConstanciaPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContratoLocacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContratoRepresentante")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContratoResponsableSH")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CopiaConvenioCNC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CronogramaObra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CuadroPotencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CuadroVerifConduc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FactAmbienteBA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaEmision")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaTasaA")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdEstadoTramite")
                        .HasColumnType("integer");

                    b.Property<string>("ImpactoAmbiental")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LayoutElectrica")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LibreDeuda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicionRadiacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MemoriaCalculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreExp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NroExpediente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrdenamientoTerritorial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermisoAmbiental")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanoCivil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanoConstruccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Planos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PoderTramite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolizaSeguroCT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistroDGOP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReglamentoCopropiedad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeguridadHigiene")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeguroRespCivil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SistBaliza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SistProtAtmos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SistPuestaTierra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TasaAnual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TasaSigem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnifiliarGral")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdExpediente");

                    b.HasIndex("ANT_EstadoTramiteIdEstado");

                    b.HasIndex("IdEstadoTramite");

                    b.ToTable("ANT_Expedientes");
                });

            modelBuilder.Entity("API.DataSchema.ANT_Inspecciones", b =>
                {
                    b.Property<int>("IdInspeccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInspeccion"));

                    b.Property<string>("AlambradoPerimetral")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AnilloTierra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BalizaFlash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BarraEquipos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BarraEstructura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseConcreto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseConcretoPrin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bulones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CableAlimentacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CableDescarga")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CamaraInspeccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CamaraPararrayos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CamarasInspec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CamarasPase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CanalPilar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConexionBarra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConexionChasis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConexionEstAnillo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConexionTierra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Desmalezado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DesplaFisuras")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErosionTerreno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EscaleraGuarda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoFotocelula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoGral")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstanqueCañerias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstrTransicion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GrasaAntiox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Grietas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdAntena")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("IluminacionBanquina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LucesBaliza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mastil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjetosExtraños")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObstruccionesCaños")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PedestalConcreto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PernosFijaEstructura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PernosFijaGabinetes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PernosFijaPedestales")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PernosFijaPerfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PernosViga")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PilarMedicion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PinturaBaliza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PinturaBanquina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlataformasInspeccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PortoAcceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProteccionTermo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PuertaBanquina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PuntaCaptora")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PuntosHumedad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Razon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoturaPedestales")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SalvaCaidas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SimboloRiesgoElec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoporteBalizas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoportesBandejas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoportesCañerias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoportesFijaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableroBaliza")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableroEmergencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableroGralCA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableroPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UCLA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnionesTramos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Verticalidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VigaEquipos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Visibilidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdInspeccion");

                    b.HasIndex("IdAntena");

                    b.ToTable("ANT_Inspecciones");
                });

            modelBuilder.Entity("API.DataSchema.ANT_Prestadores", b =>
                {
                    b.Property<int>("IdPrestador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPrestador"));

                    b.Property<int>("Cuit")
                        .HasColumnType("integer");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdApoderado")
                        .HasColumnType("integer");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPrestador");

                    b.ToTable("ANT_Prestadores");
                });

            modelBuilder.Entity("API.DataSchema.ANT_TipoAntenas", b =>
                {
                    b.Property<int>("IdTipoAntena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoAntena"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdTipoAntena");

                    b.ToTable("ANT_TipoAntenas");
                });

            modelBuilder.Entity("API.DataSchema.ANT_Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("ANT_Usuarios");
                });

            modelBuilder.Entity("ANT_ApoderadosANT_Prestadores", b =>
                {
                    b.HasOne("API.DataSchema.ANT_Apoderados", null)
                        .WithMany()
                        .HasForeignKey("ApoderadosIdApoderado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DataSchema.ANT_Prestadores", null)
                        .WithMany()
                        .HasForeignKey("PrestadorIdPrestador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.DataSchema.ANT_Antenas", b =>
                {
                    b.HasOne("API.DataSchema.ANT_Prestadores", "Prestador")
                        .WithMany("Antenas")
                        .HasForeignKey("IdPrestador");

                    b.HasOne("API.DataSchema.ANT_TipoAntenas", "TipoAntenas")
                        .WithMany("Antenas")
                        .HasForeignKey("IdTipoAntena")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");

                    b.Navigation("TipoAntenas");
                });

            modelBuilder.Entity("API.DataSchema.ANT_Expedientes", b =>
                {
                    b.HasOne("API.DataSchema.ANT_EstadoTramite", null)
                        .WithMany("Expedientes")
                        .HasForeignKey("ANT_EstadoTramiteIdEstado");

                    b.HasOne("API.DataSchema.ANT_EstadoTramite", "EstadoTramite")
                        .WithMany()
                        .HasForeignKey("IdEstadoTramite");

                    b.HasOne("API.DataSchema.ANT_Antenas", null)
                        .WithOne("Expediente")
                        .HasForeignKey("API.DataSchema.ANT_Expedientes", "IdExpediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoTramite");
                });

            modelBuilder.Entity("API.DataSchema.ANT_Inspecciones", b =>
                {
                    b.HasOne("API.DataSchema.ANT_Antenas", "Antena")
                        .WithMany("Inspecciones")
                        .HasForeignKey("IdAntena")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antena");
                });

            modelBuilder.Entity("API.DataSchema.ANT_Antenas", b =>
                {
                    b.Navigation("Expediente");

                    b.Navigation("Inspecciones");
                });

            modelBuilder.Entity("API.DataSchema.ANT_EstadoTramite", b =>
                {
                    b.Navigation("Expedientes");
                });

            modelBuilder.Entity("API.DataSchema.ANT_Prestadores", b =>
                {
                    b.Navigation("Antenas");
                });

            modelBuilder.Entity("API.DataSchema.ANT_TipoAntenas", b =>
                {
                    b.Navigation("Antenas");
                });
#pragma warning restore 612, 618
        }
    }
}
