// <auto-generated />
using System;
using API.DataSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.DataSchema.MEC_CabeceraLiquidacion", b =>
                {
                    b.Property<int>("IdCabecera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("AnioLiquidacion")
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<DateTime>("FinLiquidacion")
                        .HasColumnType("DateTime")
                        .IsFixedLength();

                    b.Property<DateTime>("InicioLiquidacion")
                        .HasColumnType("DateTime")
                        .IsFixedLength();

                    b.Property<string>("MesLiquidacion")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .IsFixedLength();

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength();

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int>("idTipoLiquidacion")
                        .HasColumnType("integer");

                    b.HasKey("IdCabecera");

                    b.ToTable("MEC_CabeceraLiquidacion");
                });

            modelBuilder.Entity("API.DataSchema.MEC_CarRevista", b =>
                {
                    b.Property<int>("IdCarRevista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCarRevista"));

                    b.Property<string>("CodMgp")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("CodPcia")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength(false);

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdCarRevista");

                    b.ToTable("MEC_CarRevista");
                });

            modelBuilder.Entity("API.DataSchema.MEC_Conceptos", b =>
                {
                    b.Property<int>("IdConcepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConcepto"));

                    b.Property<string>("CodConcepto")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<string>("CodConceptoMgp")
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("ConAporte")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength(false);

                    b.Property<string>("Patronal")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdConcepto");

                    b.ToTable("MEC_Conceptos");
                });

            modelBuilder.Entity("API.DataSchema.MEC_Establecimientos", b =>
                {
                    b.Property<int>("IdEstablecimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("CantSecciones")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("CantTurnos")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<int>("IdTipoEstablecimiento")
                        .HasColumnType("integer");

                    b.Property<string>("NombreMgp")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("NombrePcia")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("NroDiegep")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<string>("NroEstablecimiento")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength(false);

                    b.Property<string>("Ruralidad")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Subvencion")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength(false);

                    b.Property<string>("UE")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength(false);

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdEstablecimiento");

                    b.HasIndex("IdTipoEstablecimiento");

                    b.ToTable("MEC_Establecimientos");
                });

            modelBuilder.Entity("API.DataSchema.MEC_POF", b =>
                {
                    b.Property<int>("IdPOF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPOF"));

                    b.Property<string>("AntigAnios")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("AntigMeses")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Barra")
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("CantHsCargo")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("IdEstablecimiento")
                        .HasColumnType("integer");

                    b.Property<int>("IdPersona")
                        .HasColumnType("integer");

                    b.Property<string>("Secuencia")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<string>("SinHaberes")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Subvencionada")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("TipoCargo")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdPOF");

                    b.ToTable("MEC_POF");
                });

            modelBuilder.Entity("API.DataSchema.MEC_Personas", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("char(8)")
                        .IsFixedLength();

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdPersona");

                    b.ToTable("MEC_Personas");
                });

            modelBuilder.Entity("API.DataSchema.MEC_TMPMecanizadas", b =>
                {
                    b.Property<int>("idTMPMecanizada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idTMPMecanizada"));

                    b.Property<string>("AnioMesAfectacion")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("CaracterRevista")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("CodigoLiquidacion")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("Dependencia")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<DateTime?>("FechaImportacion")
                        .HasColumnType("DateTime")
                        .IsFixedLength();

                    b.Property<string>("Funcion")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<decimal?>("HorasDesignadas")
                        .IsRequired()
                        .HasColumnType("decimal")
                        .IsFixedLength();

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal")
                        .IsFixedLength();

                    b.Property<string>("MarcaTransferido")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("MesLiquidacion")
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("NroEstab")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("OrdenPago")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("RegimenEstatutario")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("RegistroValido")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Secuencia")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("Signo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("Subvencion")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("TipoCargo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<string>("TipoOrganizacion")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .IsFixedLength();

                    b.Property<int>("idCabecera")
                        .HasColumnType("integer");

                    b.HasKey("idTMPMecanizada");

                    b.ToTable("MEC_TMPMecanizadas");
                });

            modelBuilder.Entity("API.DataSchema.MEC_TiposCategorias", b =>
                {
                    b.Property<int>("IdTipoCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("CodCategoria")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("CodCategoriaMGP")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdTipoCategoria");

                    b.ToTable("MEC_TiposCategorias");
                });

            modelBuilder.Entity("API.DataSchema.MEC_TiposEstablecimientos", b =>
                {
                    b.Property<int>("IdTipoEstablecimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoEstablecimiento"));

                    b.Property<string>("CodTipoEstablecimiento")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength(false);

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdTipoEstablecimiento");

                    b.ToTable("MEC_TiposEstablecimientos");
                });

            modelBuilder.Entity("API.DataSchema.MEC_TiposFunciones", b =>
                {
                    b.Property<int>("IdTipoFuncion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoFuncion"));

                    b.Property<string>("CodFuncion")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("CodFuncionMGP")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdTipoFuncion");

                    b.ToTable("MEC_TiposFunciones");
                });

            modelBuilder.Entity("API.DataSchema.MEC_TiposLiquidaciones", b =>
                {
                    b.Property<int>("IdTipoLiquidacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .IsFixedLength(false);

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdTipoLiquidacion");

                    b.ToTable("MEC_TiposLiquidaciones");
                });

            modelBuilder.Entity("API.DataSchema.MEC_CabeceraLiquidacion", b =>
                {
                    b.HasOne("API.DataSchema.MEC_TMPMecanizadas", null)
                        .WithOne("Cabecera")
                        .HasForeignKey("API.DataSchema.MEC_CabeceraLiquidacion", "IdCabecera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.DataSchema.MEC_Establecimientos", b =>
                {
                    b.HasOne("API.DataSchema.MEC_POF", null)
                        .WithOne("Establecimiento")
                        .HasForeignKey("API.DataSchema.MEC_Establecimientos", "IdEstablecimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.DataSchema.MEC_TiposEstablecimientos", "TipoEstablecimientos")
                        .WithMany("Establecimientos")
                        .HasForeignKey("IdTipoEstablecimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEstablecimientos");
                });

            modelBuilder.Entity("API.DataSchema.MEC_Personas", b =>
                {
                    b.HasOne("API.DataSchema.MEC_POF", null)
                        .WithOne("Persona")
                        .HasForeignKey("API.DataSchema.MEC_Personas", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.DataSchema.MEC_TiposCategorias", b =>
                {
                    b.HasOne("API.DataSchema.MEC_POF", null)
                        .WithOne("Categoria")
                        .HasForeignKey("API.DataSchema.MEC_TiposCategorias", "IdTipoCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.DataSchema.MEC_TiposLiquidaciones", b =>
                {
                    b.HasOne("API.DataSchema.MEC_CabeceraLiquidacion", null)
                        .WithOne("TipoLiquidacion")
                        .HasForeignKey("API.DataSchema.MEC_TiposLiquidaciones", "IdTipoLiquidacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.DataSchema.MEC_CabeceraLiquidacion", b =>
                {
                    b.Navigation("TipoLiquidacion");
                });

            modelBuilder.Entity("API.DataSchema.MEC_POF", b =>
                {
                    b.Navigation("Categoria");

                    b.Navigation("Establecimiento");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("API.DataSchema.MEC_TMPMecanizadas", b =>
                {
                    b.Navigation("Cabecera");
                });

            modelBuilder.Entity("API.DataSchema.MEC_TiposEstablecimientos", b =>
                {
                    b.Navigation("Establecimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
