// <auto-generated />
using API.DataSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.DataSchema.MEC_CarRevista", b =>
                {
                    b.Property<int>("IdCarRevista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCarRevista"));

                    b.Property<string>("CodMgp")
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("CodPcia")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength(false);

                    b.HasKey("IdCarRevista");

                    b.ToTable("MEC_CarRevista");
                });

            modelBuilder.Entity("API.DataSchema.MEC_Conceptos", b =>
                {
                    b.Property<int>("IdConcepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConcepto"));

                    b.Property<string>("CodConcepto")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .IsFixedLength();

                    b.Property<string>("CodConceptoMgp")
                        .HasColumnType("varchar(10)")
                        .IsFixedLength(false);

                    b.Property<string>("ConAporte")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .IsFixedLength(false);

                    b.Property<string>("Patronal")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Vigente")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("IdConcepto");

                    b.ToTable("MEC_Conceptos");
                });
#pragma warning restore 612, 618
        }
    }
}
